// Chapter 1 — Securing Data in Transit
// Format: topic -> [question, [correct, why], [wrong, why], [wrong, why], [wrong, why]]
// The correct option is always listed first here; the app shuffles options when displayed.
addChapter({
  id: "ch1",
  number: "1",
  title: "Securing Data in Transit",
  topics: {
    "Passive vs. active attacks": [
      ["An attacker plugs a laptop into a switch's SPAN port and silently records traffic without changing anything. Which property is lost, and which control prevents it?",
        ["Confidentiality; encrypt the traffic in transit", "A passive attack reads but never modifies traffic, so the loss is confidentiality. Encryption (TLS, SSH, IPsec) makes the captured bytes useless ciphertext."],
        ["Integrity; add digital signatures to every message", "Nothing was altered, so integrity is intact. Signatures detect modification but do not stop someone from reading plaintext."],
        ["Availability; add redundant network links", "Silent recording does not disrupt service, so availability is unaffected."],
        ["Authenticity; enable endpoint authentication", "Endpoint authentication defeats an active man-in-the-middle, but a passive recorder still reads unencrypted traffic no matter who the endpoints are."]],
      ["An employee says, \"Our office uses switches, not hubs, so nobody on the LAN can sniff my traffic.\" Which technique proves this wrong?",
        ["ARP cache poisoning", "ARP poisoning maps the gateway's IP to the attacker's MAC, so a switch faithfully delivers victims' traffic to the attacker. That defeats the myth that switching prevents sniffing."],
        ["DNSSEC zone signing on the local resolver", "DNSSEC is a defense that signs DNS records; it does not redirect LAN traffic."],
        ["Certificate pinning in the user's browser", "Pinning is a client-side defense against fraudulent certificates, not a sniffing technique."],
        ["Ingress filtering at the edge router", "Ingress filtering is a defensive control that drops spoofed inbound packets."]],
      ["What best distinguishes an active attack from a passive one?",
        ["The attacker can alter, inject, or replay traffic", "Active attacks (MITM, replay, downgrade) modify the conversation. Passive attacks only observe, costing confidentiality."],
        ["The attacker records traffic to analyze offline later", "Recording for later analysis is the definition of a passive attack."],
        ["The attacker must have physical access to the cabling", "Both kinds can be carried out remotely, for example from a compromised router or rogue AP."],
        ["Active attacks are easier to prevent with encryption alone", "Encryption alone stops passive eavesdropping. Active attacks additionally need endpoint authentication."]],
      ["An attacker relaying a TLS handshake removes the strong cipher suites from the client's offer so both sides settle on a weak one. What is this attack?",
        ["Downgrade attack", "Forcing both sides down to weaker (or no) encryption is a downgrade attack, a form of active MITM. TLS 1.3 removed the legacy ciphers that made this easy."],
        ["Replay attack", "Replay resends previously captured valid messages; it doesn't negotiate weaker crypto."],
        ["Birthday attack", "A birthday attack searches for hash collisions; it is unrelated to cipher negotiation."],
        ["Passive eavesdropping", "Editing the handshake is modification, which makes it an active attack."]],
      ["Traffic between two branch offices is quietly copied at a compromised transit provider's router. What kind of interception position is this?",
        ["An upstream position on the path", "A compromised gateway, ISP, transit provider, or malicious cloud neighbor is an upstream position that enables passive interception without touching either LAN."],
        ["A SPAN port on the local switch", "A SPAN port is on a local switch inside the network, not at a transit provider."],
        ["An evil-twin access point", "An evil twin is a rogue Wi-Fi AP near the victim, not a provider's router."],
        ["A keylogger on the endpoint", "A keylogger lives on the endpoint itself, not in the network path."]],
      ["Encryption has stopped a passive eavesdropper. What additional control is required to stop an active adversary-in-the-middle?",
        ["Endpoint authentication (certificate or host-key checks)", "An AiTM terminates each leg and re-encrypts, so each leg is encrypted to the attacker. Only verifying who is on the other end (certificate, host key, pinning) defeats it."],
        ["Longer encryption keys on both endpoints", "Key length doesn't matter if you're negotiating keys with the attacker in the first place."],
        ["Switching the cipher from AES to ChaCha20", "Swapping one strong cipher for another doesn't address who you are talking to."],
        ["Compressing traffic before it is encrypted", "Compression has nothing to do with endpoint identity (and can even leak information)."]],
      ["At a conference, attendees join \"Conference-WiFi\", an access point the attacker set up with the same name and a stronger signal than the real one. What is this?",
        ["An evil-twin (rogue) access point", "An evil twin mimics a trusted SSID so clients associate with it, giving the attacker a man-in-the-middle position on their traffic."],
        ["A DHCP starvation attack on the venue", "DHCP starvation exhausts an address pool with spoofed requests. It doesn't impersonate a network name."],
        ["VLAN hopping through the venue's switches", "VLAN hopping abuses 802.1Q trunk tagging on wired switches."],
        ["DNS cache poisoning of the venue resolver", "Cache poisoning injects forged records into a DNS resolver."]]
    ],

    "Symmetric, asymmetric & hybrid crypto": [
      ["Why does TLS use asymmetric cryptography during the handshake but symmetric cryptography for the actual data?",
        ["Asymmetric solves key exchange but is slow; symmetric is fast", "This is hybrid cryptography: public-key operations hand off (or agree on) keys, then fast ephemeral symmetric session keys like AES protect the payload."],
        ["Symmetric crypto is more secure than asymmetric crypto", "Security isn't the reason. Both are secure when used properly; the split is about speed vs. key distribution."],
        ["Asymmetric algorithms can only encrypt a single packet", "Asymmetric algorithms can encrypt more data. They're just far too slow to use for bulk traffic."],
        ["Symmetric keys can be shared publicly without risk", "A symmetric key must stay secret. Anyone holding it can decrypt."]],
      ["A 100-person company wants every pair of employees to have a private channel using only symmetric keys. How many keys are needed?",
        ["4,950", "Pairwise symmetric keys require n(n−1)/2 = 100 × 99 / 2 = 4,950 keys. That explosion is the key distribution problem."],
        ["200", "200 is 2n, the count for asymmetric crypto (one public and one private key per person)."],
        ["100", "One key per person only works with asymmetric pairs, and even then it's two keys each."],
        ["9,900", "9,900 is n(n−1) without dividing by 2, so it counts every pair twice."]],
      ["A 100-person company gives every employee a public/private key pair so anyone can message anyone privately. How many keys are needed in total?",
        ["200", "Each person needs one key pair (public + private), so 2n = 200. That's the escape from the symmetric key explosion."],
        ["4,950", "4,950 is the pairwise symmetric count n(n−1)/2."],
        ["100", "Each person needs both a public and a private key, not one key."],
        ["10,000", "n² overcounts badly; asymmetric scales linearly with 2n."]],
      ["Alice wants to send Bob a message that only Bob can read. Which key does Alice use to encrypt it?",
        ["Bob's public key", "Anything encrypted with Bob's public key can only be decrypted with Bob's private key, which only Bob holds."],
        ["Bob's private key", "Alice never has Bob's private key. It must stay secret to Bob."],
        ["Alice's private key", "Encrypting with Alice's private key is signing. Anyone with Alice's public key could decrypt it, so it isn't confidential."],
        ["Alice's public key", "Only Alice's private key could decrypt that, so Bob couldn't read it."]],
      ["Which of the following is a symmetric algorithm?",
        ["AES", "AES (FIPS 197) uses one shared key to encrypt and decrypt. It's the workhorse for bulk data in nearly every secure protocol."],
        ["RSA", "RSA is asymmetric, based on factoring large numbers."],
        ["Elliptic-curve cryptography (ECC)", "ECC is asymmetric, based on the elliptic-curve discrete logarithm problem."],
        ["Diffie–Hellman", "Diffie–Hellman is an asymmetric key-agreement method, not a symmetric cipher."]],
      ["According to the notes, what is the core weakness of symmetric encryption?",
        ["Getting the shared key to the other party securely", "Symmetric crypto is fast and strong, but both sides must already share a secret. Getting it there safely is the key distribution problem that asymmetric crypto solves."],
        ["It is too slow to protect large volumes of data", "Symmetric encryption is the fast option. That's why it carries the bulk payload."],
        ["It cannot provide confidentiality for stored data", "Confidentiality is exactly what symmetric encryption provides."],
        ["It requires a certificate authority for every message", "CAs belong to PKI and authenticate public keys. Symmetric ciphers don't use them per message."]],
      ["A private key is described as \"the mirror image of public-key encryption\" when used for which purpose?",
        ["Creating a digital signature", "Encrypting for confidentiality uses the recipient's public key. Signing flips it: the sender uses their own private key, and anyone verifies with the public key."],
        ["Encrypting bulk session traffic", "Bulk traffic uses symmetric session keys, not a private key."],
        ["Hashing passwords for storage", "Password hashing uses slow, salted hash functions with no key pair."],
        ["Performing frequency analysis", "Frequency analysis is a cryptanalysis technique against classical ciphers."]]
    ],

    "Key exchange & forward secrecy": [
      ["An attacker records a year of a server's encrypted ECDHE sessions, then steals the server's long-term private key. What can they now decrypt?",
        ["None of them, thanks to forward secrecy", "With ephemeral Diffie–Hellman, each session's key was derived from throwaway values that were discarded. The long-term key only authenticated the server, so past sessions stay unreadable."],
        ["Every session recorded during that year", "That would be true for static key exchange, not ephemeral ECDHE."],
        ["Only the sessions from the last 30 days", "There's no time window. Forward secrecy protects all past sessions equally."],
        ["Any session whose certificate they also obtain", "The certificate is public anyway, so it gives the attacker nothing new."]],
      ["A legacy server encrypts each session key directly under its long-term RSA key (static key exchange). The RSA private key later leaks. What is the impact on previously recorded traffic?",
        ["All of it, because there was no forward secrecy", "With static key exchange the long-term key unwraps every session key ever sent, so a single key theft exposes the entire recorded history."],
        ["None, since each session used a different session key", "Different session keys don't help when every one of them was protected by the same stolen RSA key."],
        ["Only future sessions, not past recorded ones", "Past recorded sessions are at risk too. That is exactly what forward secrecy would have prevented."],
        ["Only sessions that were hashed with SHA-1", "The hash algorithm is irrelevant. The exposure comes from the key exchange design."]],
      ["What does a Diffie–Hellman key exchange allow two parties to do?",
        ["Agree on a shared secret over a public channel without revealing it", "DH (and its elliptic-curve form ECDHE) lets both sides compute the same secret from exchanged public values; the observer can't reconstruct it."],
        ["Prove that a sender cannot deny sending a message", "Nonrepudiation comes from digital signatures, not key exchange."],
        ["Authenticate the server's identity with no certificate", "Plain DH has no authentication. It must be combined with a certificate or host key to stop a MITM."],
        ["Store password hashes securely in a database", "Password storage uses slow, salted hashes, not DH."]],
      ["Two parties run an unauthenticated Diffie–Hellman exchange. What attack remains possible?",
        ["An adversary-in-the-middle", "Without authentication, each party unknowingly agrees on a key with the attacker, who relays and reads everything. That's why TLS signs the exchange with the server's certificate key and SSH uses host keys."],
        ["Frequency analysis of the ciphertext", "Frequency analysis breaks classical substitution ciphers, not modern key exchange."],
        ["A rainbow-table attack on the exchanged keys", "Rainbow tables reverse unsalted password hashes."],
        ["A birthday attack on the shared secret", "Birthday attacks target hash collisions, not DH key agreement."]],
      ["Which TLS version made forward secrecy mandatory?",
        ["TLS 1.3", "TLS 1.3 (2018) removed static RSA key exchange and legacy ciphers, so every handshake uses ephemeral (EC)DHE and provides forward secrecy."],
        ["TLS 1.2", "TLS 1.2 supports ECDHE but still permits non-forward-secret static RSA key exchange."],
        ["TLS 1.0", "TLS 1.0 is deprecated (SP 800-52 Rev 2) and does not require forward secrecy."],
        ["SSL 3.0", "SSL 3.0 is long obsolete and insecure."]],
      ["What does \"ephemeral\" mean in a key exchange like ECDHE?",
        ["New keys are generated per session, then discarded", "Ephemeral keys don't last. Because they're thrown away, stealing a long-term key later can't recreate them, which is what gives forward secrecy."],
        ["The key is stored in a hardware security module", "HSM storage is about protecting long-lived keys, the opposite of ephemeral."],
        ["The key is signed by a certificate authority", "CAs sign certificates (long-term identity), not per-session ephemeral values."],
        ["The key is derived from the user's password", "Password-derived keys are a different concept (KDFs like PBKDF2)."]],
      ["Which statement about the server's long-term private key in a TLS 1.3 handshake is correct?",
        ["It only authenticates the server; ephemeral keys protect the data", "In TLS 1.3 the long-term key's job is authentication. Confidentiality comes from ephemeral (EC)DHE keys, so stealing the long-term key doesn't expose past traffic."],
        ["It directly encrypts all of the application data", "Application data is encrypted with fast symmetric session keys, never the private key."],
        ["It is sent to the client so both sides share it", "A private key is never transmitted. Only the certificate's public key is sent."],
        ["It is regenerated fresh for every new session", "That describes ephemeral keys. The long-term key persists in the certificate."]]
    ],

    "Hashes, MACs & digital signatures": [
      ["Two partners share an HMAC key. A disputed message arrives with a valid HMAC, and each partner claims the other sent it. Why can't the HMAC settle the dispute?",
        ["Both hold the same key, so either could have made it", "A MAC proves the message is intact and came from a key holder, but because the key is shared it can't prove which holder. Either side could forge a message and blame the other. A digital signature is needed."],
        ["HMACs do not provide any integrity protection", "HMACs do provide integrity. Any change breaks the tag."],
        ["HMACs use a public key, so anyone could create one", "HMACs use a shared secret key, not a public key."],
        ["The HMAC encrypts the message and hides the sender", "An HMAC doesn't encrypt anything. It's a keyed hash attached to the message."]],
      ["How does a sender create a digital signature?",
        ["Hash the message, then encrypt the digest with the sender's own private key", "The encrypted digest is the signature. Only the sender's private key could produce it, and anyone can check it with the sender's public key."],
        ["Encrypt the whole message with the recipient's public key", "That provides confidentiality for the recipient, not a signature."],
        ["Hash the message and encrypt the digest with the recipient's public key", "Using the recipient's key proves nothing about who sent it."],
        ["Encrypt the digest with a secret key shared with the recipient", "A shared secret key makes this a MAC, which can't provide nonrepudiation."]],
      ["How does a recipient verify a digital signature?",
        ["Compare its own hash with the signature decrypted by the sender's public key", "Matching digests prove the message is unchanged and came from the private key holder."],
        ["Decrypt the signature with the recipient's own private key and read it", "The recipient's private key has nothing to do with the sender's signature."],
        ["Ask the sender to securely re-send their private key for checking", "Private keys are never shared. Verification only needs the public key."],
        ["Re-encrypt the message with the sender's private key and compare", "The recipient doesn't have the sender's private key."]],
      ["Which three guarantees does a valid digital signature provide?",
        ["Integrity, authentication of origin, and nonrepudiation", "Any change breaks the digest match (integrity), only the private key holder could sign (origin), and the signer can't plausibly deny it (nonrepudiation)."],
        ["Confidentiality, integrity, and availability", "A signature doesn't hide content (no confidentiality) and doesn't affect availability."],
        ["Confidentiality, nonrepudiation, and forward secrecy", "Signatures provide no confidentiality, and forward secrecy is a key exchange property."],
        ["Authorization, accounting, and availability", "These aren't properties of a digital signature."]],
      ["A contract is digitally signed but sent unencrypted by email. What can an eavesdropper on the path do?",
        ["Read it, but not alter it undetected", "Signatures give integrity and origin, not confidentiality. The content is readable, but it can't be altered without detection."],
        ["Nothing, because a signature encrypts the message", "A signature encrypts only the digest, not the message itself."],
        ["Modify the contract without anyone detecting it", "Any modification changes the hash, so the signature no longer matches."],
        ["Forge a new signature using the sender's public key", "You can't sign with a public key. Signing requires the sender's private key."]],
      ["A modern protocol uses AES-GCM. An attacker flips bits in the ciphertext in transit. What happens?",
        ["The receiver detects the tampering and rejects the message instead of decrypting it", "AES-GCM is an AEAD mode. Its built-in authentication tag makes tampered ciphertext fail verification, so it's rejected rather than silently decrypted."],
        ["The receiver decrypts it to slightly altered plaintext without noticing", "That's the risk with unauthenticated encryption modes. AEAD exists to prevent it."],
        ["The receiver automatically repairs the flipped bits", "Encryption modes don't do error correction."],
        ["The connection falls back to unencrypted mode", "A failed integrity check doesn't downgrade to plaintext; the message is rejected."]],
      ["What does AEAD (e.g., ChaCha20-Poly1305) provide that encryption alone does not?",
        ["Integrity and authenticity, alongside confidentiality", "Authenticated encryption with associated data combines encryption and a MAC-like tag, so the data is both hidden and tamper-evident."],
        ["Nonrepudiation of whoever sent the message", "AEAD uses a shared symmetric key, so like a MAC it can't prove which party sent the message."],
        ["Forward secrecy for previously recorded sessions", "Forward secrecy comes from ephemeral key exchange, not the cipher mode."],
        ["Compression of the data before it is sent", "AEAD doesn't compress anything."]],
      ["Which is a true property of a cryptographic hash function?",
        ["It is one-way and always produces a fixed-length output", "A hash maps any input to a fixed-size digest (SHA-256 is always 256 bits), and reversing it is computationally infeasible."],
        ["It can be reversed by anyone who holds the key", "Hashes have no key and aren't reversible. That's encryption."],
        ["Its output grows longer as the input grows", "Output length is fixed regardless of input size."],
        ["It provides confidentiality for the data it fingerprints", "A hash is a fingerprint, not a hiding mechanism. The original data is still sent or stored separately."]],
      ["An attacker modifies a downloadable file and replaces the published SHA-256 hash with a new one computed over the modified file. Which mechanism would have prevented this undetected swap?",
        ["An HMAC or digital signature over the file", "A plain hash has no secret, so anyone can recompute it. A keyed MAC or a private-key signature can't be regenerated by the attacker."],
        ["Publishing a SHA-512 hash instead of SHA-256", "A longer hash still has no secret. The attacker simply recomputes SHA-512."],
        ["Publishing an MD5 hash instead of SHA-256", "MD5 is weaker and still keyless."],
        ["Compressing the file before hashing it", "Compression doesn't add a secret, so the attacker recomputes anyway."]]
    ],

    "SSH": [
      ["Which SSH layer authenticates the server's host key, runs the Diffie–Hellman exchange, and turns on authenticated encryption?",
        ["The transport layer (RFC 4253)", "The transport layer establishes the secure, server-authenticated pipe that everything else runs inside."],
        ["The user-authentication layer (RFC 4252)", "This layer authenticates the client (by password or public key), after the transport is set up."],
        ["The connection layer (RFC 4254)", "This layer multiplexes shells, file transfer, and port forwarding over the already-encrypted pipe."],
        ["The presentation layer", "That's an OSI model layer, not one of SSH's three protocol layers."]],
      ["Which SSH layer multiplexes interactive shells, file transfers, and port forwarding over one encrypted pipe?",
        ["The connection layer (RFC 4254)", "Once the transport is secure and the user is authenticated, the connection layer carries multiple channels inside the single tunnel."],
        ["The transport layer (RFC 4253)", "The transport layer authenticates the server and sets up encryption. It doesn't manage channels."],
        ["The user-authentication layer (RFC 4252)", "This layer only authenticates the client."],
        ["The session layer", "That's an OSI term, not an SSH layer."]],
      ["The first time you SSH to a new server, the client shows its key fingerprint and asks you to confirm. What trust model is this?",
        ["Trust on first use (TOFU)", "SSH accepts the host key on first contact and records it in known_hosts, then checks it on every later connection."],
        ["A PKI chain of trust", "PKI (used by TLS) relies on CA-signed certificates rather than a first-contact prompt."],
        ["Certificate pinning by a CA", "Pinning ties a client to a specific certificate or key; it isn't the first-contact prompt."],
        ["Mutual TLS", "SSH isn't TLS, and this prompt isn't a certificate exchange."]],
      ["An admin connects daily to a server and today sees \"WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!\" Nothing was announced. What is the best response?",
        ["Stop and verify the new key out-of-band first", "A host key mismatch is SSH's loud warning that someone else may be answering. Confirm with the server owner through a separate channel before trusting it."],
        ["Delete the old known_hosts entry and reconnect", "That throws away the protection and accepts whatever key is presented, possibly the attacker's."],
        ["Switch to password authentication to avoid the warning", "The warning is about the server's identity. Switching to password login would hand an impostor your password."],
        ["Ignore it, since host keys change after every reboot", "Host keys are persistent. Reboots don't change them."]],
      ["Where does an SSH client store the host keys it has accepted?",
        ["known_hosts", "The client records each server's host key fingerprint in known_hosts and compares against it on every later connection."],
        ["authorized_keys", "authorized_keys is on the server and lists the user public keys allowed to log in."],
        ["/etc/passwd", "That's the Unix account file, unrelated to SSH host keys."],
        ["The SAM hive", "The SAM stores Windows local account hashes."]],
      ["With SSH public-key authentication, what does the server store for the user?",
        ["The user's public key, in authorized_keys", "The server only needs the public half to check the user's signed challenge. Nothing on the server can be stolen and reused to log in."],
        ["The user's private key", "The private key never leaves the client. Storing it on the server would defeat the purpose."],
        ["A salted hash of the user's password", "That's for password authentication, not public-key authentication."],
        ["A copy of the CA's root certificate", "Basic SSH public-key auth doesn't involve a CA."]],
      ["Why is SSH public-key authentication more resistant to credential theft than password authentication?",
        ["The private key never crosses the network or sits on the server", "Passwords cross the network (encrypted) and are verified by the server. With keys, only a signature crosses, and the server holds only a public key."],
        ["Passwords are sent in cleartext over SSH sessions", "SSH encrypts passwords in transit. The issue is that the password is still a reusable secret the server receives."],
        ["Public keys never expire, so they can't be guessed", "Expiry isn't the point. The protection comes from never transmitting the private key."],
        ["It disables host-key checking for faster logins", "Public-key auth has nothing to do with disabling host-key checks, and disabling them would be dangerous."]],
      ["An administrator keeps team SSH private keys in a plaintext file on a shared drive. What practice should replace this?",
        ["Use an agent, secrets manager, or vault, and rotate keys", "Private keys must be handled like passwords: never in plaintext files, inventoried, rotated, and removed on offboarding."],
        ["Rename the file so it's much harder to find", "Hiding the file is security by obscurity. Anyone who finds it still has the keys."],
        ["Email the keys to each admin individually instead", "Email spreads the secrets to more places and doesn't protect them."],
        ["Convert all of the logins back to passwords", "That gives up the stronger authentication method instead of fixing key handling."]],
      ["A contractor leaves the company, but their SSH public key remains in authorized_keys on 40 servers. What is the risk?",
        ["They can still log in; keys must be removed at offboarding", "The authorized_keys entry still grants access to whoever holds the matching private key, which the contractor keeps."],
        ["No risk, since public keys are meant to be public", "Publishing a public key is fine. Leaving it authorized is the problem."],
        ["The servers' host keys must be regenerated", "Host keys identify the servers. The problem is the leftover user authorization."],
        ["The risk only exists if the contractor's password was never changed", "Key-based login bypasses the password entirely."]]
    ],

    "Secure file transfer": [
      ["Which file transfer protocol is a subsystem of SSH and inherits its encryption and server authentication?",
        ["SFTP", "SFTP runs inside SSH (port 22), so it gets SSH's host-key authentication and encryption for free."],
        ["FTPS", "FTPS is the old FTP protocol wrapped in TLS, not part of SSH."],
        ["FTP", "Plain FTP (port 21) is cleartext."],
        ["TFTP", "TFTP is a minimal, unauthenticated UDP protocol with no encryption."]],
      ["A team lead says, \"We use FTPS, so it's the same as SFTP.\" What is wrong with that statement?",
        ["FTPS is FTP over TLS; SFTP runs over SSH", "Both encrypt, but they rely on different protocols and trust models (TLS certificates vs. SSH host keys)."],
        ["Nothing; they are two names for the same protocol", "They're entirely different protocols."],
        ["FTPS is unencrypted while SFTP is encrypted", "FTPS does encrypt, using TLS."],
        ["SFTP uses TLS while FTPS uses SSH", "This reverses them: SFTP rides SSH, FTPS rides TLS."]],
      ["Why is SFTP preferred over legacy SCP today?",
        ["Legacy SCP was deprecated after CVE-2019-6111", "Both ride SSH, but the legacy SCP protocol had design flaws. SFTP is the maintained, preferred choice."],
        ["SCP sends file contents in cleartext", "SCP runs over SSH, so it is encrypted. Its problem was protocol flaws, not missing encryption."],
        ["SCP only works over the deprecated TLS 1.0", "SCP uses SSH, not TLS."],
        ["SFTP doesn't require users to authenticate", "SFTP requires SSH authentication like any SSH session."]],
      ["A backup job moves files nightly with FTP on port 21. What is the main risk, and what should replace it?",
        ["It's cleartext; replace it with SFTP or FTPS", "FTP sends both the login and the file contents unencrypted. SFTP or FTPS adds encryption and server authentication."],
        ["FTP is too slow; replace it with Telnet", "Telnet is also cleartext and is a remote shell, not file transfer."],
        ["FTP can't handle large files; replace it with HTTP on port 80", "HTTP on port 80 is also cleartext."],
        ["Port 21 is blocked by default; move FTP to port 2121", "Changing the port doesn't add encryption. That's obscurity, not security."]]
    ],

    "TLS & HTTPS": [
      ["An auditor finds internal application traffic using TLS 1.0. What should be done?",
        ["Move to TLS 1.3 (or hardened 1.2) and disable old versions", "TLS 1.0 is deprecated (weak ciphers, no modern forward secrecy) and flagged by NIST SP 800-52 Rev 2. Legacy versions must be disabled so they can't be negotiated."],
        ["Fall back to SSL 3.0 for compatibility", "SSL 3.0 is older and even weaker than TLS 1.0."],
        ["Keep TLS 1.0 but use a longer certificate key", "A bigger key doesn't fix the protocol's weak ciphers and missing protections."],
        ["Leave it, since internal traffic doesn't need encryption", "Internal networks have attackers too (ARP poisoning, compromised hosts)."]],
      ["A user visits their bank over HTTPS. What can an observer on the network path still see?",
        ["Destination IP, domain name, timing, and data volume", "HTTPS encrypts the payload, not the envelope. Routing info must stay in the clear, and the hostname usually leaks via SNI."],
        ["The account number typed into the login form", "Form contents are part of the encrypted payload."],
        ["The session cookie values sent with each request", "Cookies travel inside the encrypted HTTP request."],
        ["Nothing at all, because HTTPS hides everything", "Metadata such as IPs, timing, and sizes remain visible."]],
      ["A banking site uses TLS 1.3, but a user's laptop has a keylogger. Are the user's credentials protected?",
        ["No, because HTTPS doesn't protect the endpoint", "Data is in the clear on each endpoint. Malware or a breach on either machine reads it regardless of cipher strength."],
        ["Yes, because TLS 1.3 encrypts keystrokes at the keyboard", "TLS operates on network traffic, not on keyboard input."],
        ["Yes, as long as forward secrecy is enabled", "Forward secrecy protects past sessions from later key theft, not data on a compromised endpoint."],
        ["Only if the site's certificate has expired", "Certificate status is unrelated to malware on the endpoint."]],
      ["What does the TLS handshake use to authenticate the server to the client?",
        ["An X.509 certificate signed by a trusted CA", "The server presents a CA-signed certificate binding its public key to its domain name, which the client validates."],
        ["A host key the user accepted on first use", "That's SSH's TOFU model, not TLS."],
        ["A shared password configured on both sides", "TLS server authentication uses PKI, not shared passwords."],
        ["The server's MAC address in the handshake", "MAC addresses are Layer 2 identifiers that are local to a segment and easily spoofed."]],
      ["Which describes TLS 1.3 compared to earlier versions?",
        ["It's faster, drops legacy ciphers, and mandates forward secrecy", "TLS 1.3 (2018) is the current target. It's leaner, faster, and every handshake uses ephemeral key exchange."],
        ["It removes encryption to improve performance", "TLS 1.3 never sends application data unencrypted."],
        ["It replaces certificates with SSH-style host keys", "TLS 1.3 still uses X.509 certificates."],
        ["It hides destination IP addresses from routers", "No version of TLS can hide IP headers, because routers need them to deliver packets."]],
      ["Why can't HTTPS hide a packet's destination IP address?",
        ["Routers need it in the clear to deliver the packet", "The cipher protects the cargo, not the label. The envelope has to stay readable for routing."],
        ["TLS deliberately exposes IPs for logging purposes", "It's a delivery requirement, not a logging feature."],
        ["IP addresses are too short to encrypt securely", "Length has nothing to do with it."],
        ["Certificates already contain the client's IP address", "Certificates bind to domain names, not client IPs."]],
      ["A company deploys a TLS-inspection proxy that decrypts, inspects, re-encrypts, and forwards employee HTTPS traffic. Structurally, what is it?",
        ["An authorized adversary-in-the-middle", "It terminates the session and re-originates it, which is mechanically identical to an AiTM attack. Consent is the only difference."],
        ["A passive network tap", "A tap only copies traffic. The proxy actively terminates and decrypts it."],
        ["An end-to-end encryption gateway", "It breaks end-to-end encryption rather than providing it."],
        ["A DNSSEC resolver", "DNSSEC validates DNS answers and doesn't decrypt TLS."]],
      ["TLS protects which part of a web session?",
        ["The application payload (bodies, cookies, page content)", "TLS encrypts the content of the conversation. The IP addresses, timing, and sizes outside it remain observable."],
        ["The IP addresses of both of the endpoints", "IP headers sit outside TLS and must be readable for routing."],
        ["The user's device against malware infections", "TLS protects data in transit, not the endpoint."],
        ["The DNS lookup that came before the connection", "Ordinary DNS is a separate, unencrypted exchange unless DoH/DoT is used."]]
    ],

    "Certificates & PKI": [
      ["A user finds a site's raw IP with tracert and browses to https://<that IP>. The browser shows a certificate warning even though the site is legitimate. Why?",
        ["Certificates are bound to a domain name, not an IP address", "The certificate names the domain. Visiting by IP means the name doesn't match, so validation fails."],
        ["The certificate expired the moment tracert ran", "Running tracert doesn't affect a certificate."],
        ["IP addresses cannot use TLS", "TLS works over any IP connection. The issue is name matching."],
        ["The CA revoked the certificate because of the traceroute", "Traceroute doesn't trigger revocation."]],
      ["A phishing site at paypa1-secure.com shows a valid padlock. What does its certificate actually assure?",
        ["That the server is controlled by whoever owns that domain", "A certificate proves domain control, nothing about the site's honesty or safety. Attackers can get valid certificates for look-alike domains."],
        ["That the site is operated by PayPal itself", "The certificate is for paypa1-secure.com, not PayPal's domain."],
        ["That the site was scanned and is malware-free", "CAs don't vouch for content or safety."],
        ["That a CA has verified the site is legitimate", "CA approval of a domain says nothing about intent."]],
      ["A browser refuses a connection because the server's intermediate CA does not chain up to any root the browser trusts. What failed?",
        ["The chain of trust (untrusted issuer)", "Validation walks leaf → intermediate → trusted root. If any link is untrusted, the connection is refused."],
        ["The domain's DMARC enforcement policy", "DMARC is for email sender authentication."],
        ["The host key stored in known_hosts", "known_hosts is SSH, not TLS."],
        ["The forward secrecy negotiation", "Forward secrecy concerns key exchange, not certificate trust."]],
      ["Which of the following would NOT, by itself, cause a browser to reject a server certificate?",
        ["It was signed by an intermediate CA, not directly by a root", "That's normal. Most leaf certificates are signed by intermediates that chain to a trusted root."],
        ["The name on the certificate doesn't match the site", "A name mismatch breaks validation."],
        ["The certificate's validity period has ended", "An expired certificate is rejected."],
        ["The issuing CA has revoked the certificate", "Revocation breaks the chain of trust."]],
      ["An app pins its server's certificate. Which threat does this specifically resist?",
        ["A fraudulent certificate from a trusted CA", "With pinning, the app accepts only the expected certificate or key, so even a valid-looking certificate from a compromised or rogue CA fails."],
        ["A keylogger installed on the user's phone", "Pinning protects the channel, not the endpoint."],
        ["An observer reading the app's DNS lookups", "Pinning doesn't hide DNS queries."],
        ["Attackers brute-forcing the user's password", "Password brute force is unrelated to certificate trust."]],
      ["How does TLS establish endpoint trust differently from SSH?",
        ["TLS uses CA-based PKI; SSH uses trust on first use", "TLS trusts a certificate because a trusted CA signed it. SSH trusts a key because you accepted it the first time and it hasn't changed."],
        ["TLS uses trust on first use; SSH uses CA-based PKI", "This reverses the two models."],
        ["Both identify endpoints only by their IP address", "Neither authenticates endpoints by IP address."],
        ["TLS doesn't authenticate the endpoints at all", "Endpoint authentication via certificates is a core part of the TLS handshake."]],
      ["A session is fully encrypted, yet an attacker reads everything in it. The attacker terminated the session and re-originated it to the real server. What control was missing?",
        ["Endpoint authentication (certificate or host-key validation)", "Each leg was encrypted, but to the attacker. Validating the server's identity would have exposed the impostor."],
        ["A stronger symmetric cipher for the session", "Cipher strength is irrelevant when the attacker holds the session keys."],
        ["Longer passwords for the user accounts", "The attack bypasses passwords by sitting in the middle of the session."],
        ["Compressing the data before encryption", "Compression doesn't authenticate anyone."]],
      ["A developer disables certificate validation in an API client because \"the traffic is still encrypted.\" Why is this dangerous?",
        ["A MITM can present any certificate and the client will accept it", "Confidentiality (encryption) and authenticity (endpoint authentication) are separate guarantees. Without validation you get encryption to whoever answers."],
        ["It disables the encryption on the connection entirely", "Encryption still happens. The problem is who the encrypted session is with."],
        ["It forces the client down to TLS 1.0", "Skipping validation doesn't change the protocol version."],
        ["Nothing, as long as the API runs on port 443", "The port number provides no authentication."]]
    ],

    "VPNs & IPsec": [
      ["At what layer does IPsec protect traffic?",
        ["The IP (network) layer, transparently to applications", "Unlike SSH and TLS, which protect one application's traffic, IPsec protects all IP traffic without the applications needing to change."],
        ["The application layer, one app at a time", "That describes TLS or SSH."],
        ["The physical layer, on the cable itself", "IPsec operates on IP packets, not on cabling or radio signals."],
        ["Only web traffic sent over port 443", "IPsec protects any IP traffic, not just HTTPS."]],
      ["Which IPsec mode builds site-to-site VPNs by encapsulating and encrypting entire original packets?",
        ["Tunnel mode", "Tunnel mode wraps the whole original packet (including its header) inside a new one. It's the basis of site-to-site and remote-access VPNs."],
        ["Transport mode", "Transport mode protects only the payload between two hosts and keeps the original IP header."],
        ["Monitor mode", "Monitor mode is a wireless capture setting, not an IPsec mode."],
        ["Promiscuous mode", "Promiscuous mode is a NIC setting for capturing traffic."]],
      ["When is a VPN the right tool rather than TLS or SSH?",
        ["When many protocols must cross a hostile network", "TLS and SSH secure individual applications. A VPN carries everything through one protected tunnel."],
        ["When only a single website needs to be secured", "HTTPS already covers a single website."],
        ["When you need to prove who signed a document", "That's what digital signatures are for."],
        ["When you need to store passwords securely", "Password storage needs slow, salted hashing, not a VPN."]],
      ["A remote employee's laptop uses split tunneling. What is the main security risk?",
        ["It bridges the trusted internal network and the hostile local one", "Only corporate-bound traffic is tunneled and inspected. Everything else goes out the local link, so a compromise there can pivot inward."],
        ["All traffic is slowed because everything is tunneled", "Routing everything through the tunnel is what a full tunnel does. Split tunneling saves bandwidth."],
        ["The VPN stops encrypting corporate-bound traffic", "Corporate-bound traffic is still encrypted in the tunnel."],
        ["The laptop can no longer reach the public internet", "Split tunneling sends internet traffic directly out the local link."]],
      ["Security wants every packet from remote laptops inspected by corporate controls. Which VPN configuration should be used?",
        ["Full tunnel", "A full tunnel forces all traffic through the encrypted VPN and the corporate inspection stack."],
        ["Split tunnel", "Split tunneling sends non-corporate traffic straight out the local link, uninspected."],
        ["No VPN, just HTTPS", "HTTPS protects individual sites but gives the corporation no inspection of other traffic."],
        ["Hidden SSID", "Hiding a Wi-Fi network's name has nothing to do with remote traffic inspection."]],
      ["What is the trade-off of split tunneling?",
        ["Saves bandwidth, but loses inspection and protection", "Only some traffic is protected and inspected. The rest leaves via the local, possibly hostile, connection."],
        ["It improves security but uses more bandwidth", "That describes a full tunnel."],
        ["It removes the need for VPN authentication", "VPN authentication is still required."],
        ["It encrypts traffic twice for extra safety", "Split tunneling encrypts less traffic, not more."]],
      ["An employee in a coffee shop connects to the corporate full-tunnel VPN and visits a website. From the website's point of view, where does the traffic come from?",
        ["The organization's network", "A VPN makes it look like you're on the private network, so traffic emerges from the organization's egress rather than the coffee shop's Wi-Fi."],
        ["The coffee shop's public IP", "That would happen with no VPN, or with split tunneling for that destination."],
        ["The employee's home ISP", "The employee isn't at home, and the tunnel exits at the organization."],
        ["The certificate authority", "CAs sign certificates and don't relay traffic."]]
    ],

    "Email authentication": [
      ["What does SPF check?",
        ["Whether the sending server's IP is authorized by the domain", "Sender Policy Framework asks, \"Is this coming from an IP the domain authorized?\" using a DNS-published list."],
        ["Whether the message body has a valid digital signature", "Checking a signature is DKIM's job."],
        ["Whether the message was encrypted end to end", "SPF doesn't involve encryption."],
        ["What to do with messages that fail checks", "Failure policy is set by DMARC."]],
      ["Which email control adds a digital signature over the message using the domain's private key, verifiable with a public key published in DNS?",
        ["DKIM", "DomainKeys Identified Mail uses the hash-then-sign-with-private-key construction to prove the message wasn't altered and came from the domain."],
        ["SPF", "SPF checks the sending IP against an allow-list. It has no signature."],
        ["DMARC", "DMARC sets policy and reporting. It doesn't sign messages itself."],
        ["S/MIME encryption", "S/MIME is end-to-end encryption and signing by individual users, not the domain DNS control described here."]],
      ["What does DMARC add on top of SPF and DKIM?",
        ["A policy for failed checks (none, quarantine, reject) and reporting", "DMARC turns sender authentication from advisory into a gate and tells receivers where to send reports."],
        ["Encryption of email while it is in transit", "None of SPF, DKIM, or DMARC encrypt email."],
        ["A second digital signature over each message", "DMARC relies on DKIM's signature and doesn't add its own."],
        ["Spam filtering based on the message content", "DMARC evaluates authentication results, not message content."]],
      ["A company has deployed SPF, DKIM, and DMARC. Is customer email now encrypted in transit?",
        ["No; they authenticate the sender but don't encrypt anything", "Sender authentication and confidentiality are separate concerns."],
        ["Yes, because DKIM encrypts the message body", "DKIM signs the message. It does not encrypt it."],
        ["Yes, because DMARC requires TLS for delivery", "DMARC sets failure policy. It doesn't mandate encryption."],
        ["Only messages sent from SPF-listed IPs", "SPF just checks IPs. It doesn't encrypt anything."]],
      ["A domain's DMARC record is set to p=none, and spoofed messages still land in customers' inboxes. Why?",
        ["p=none only monitors; it doesn't tell receivers to block", "With none, receivers only report failures and still deliver the mail. Enforcement is what makes DMARC a gate."],
        ["SPF results are overriding the DMARC policy", "DMARC builds on SPF results and doesn't get overridden by them."],
        ["The DKIM keys are too short to be verified", "Spoofed mail fails verification. With p=none, receivers simply aren't told to act on the failure."],
        ["DMARC only applies to encrypted mail", "DMARC applies to all mail claiming to be from the domain."]],
      ["Where are SPF, DKIM, and DMARC records published?",
        ["In the domain's DNS", "All three are DNS records, which receivers look up when evaluating incoming mail."],
        ["In each user's mailbox settings", "These are domain-level controls, not per-user settings."],
        ["In the TLS certificate", "Certificates bind keys to names for TLS. Email authentication records live in DNS."],
        ["In the SMTP message body", "Receivers look them up in DNS. They aren't carried in the body."]],
      ["Which option provides end-to-end confidentiality for an email's content?",
        ["PGP or S/MIME", "End-to-end encryption protects content from sender to recipient, including at intermediate mail servers."],
        ["DMARC", "DMARC is a sender-authentication policy with no encryption."],
        ["SPF", "SPF checks sending IPs with no encryption."],
        ["SMTP over TLS", "SMTP over TLS encrypts each hop, but every mail server along the way sees plaintext, so it isn't end-to-end."]]
    ],

    "MFA & out-of-band channels": [
      ["Why is SMS considered a weak channel for MFA codes?",
        ["It can be intercepted or hijacked via SIM-swap", "SMS isn't a strong out-of-band channel because it can be intercepted or redirected to an attacker's SIM."],
        ["SMS codes are always too short to be secure", "Code length isn't the core problem. The channel itself is weak."],
        ["SMS cannot deliver codes internationally", "Availability isn't the security concern here."],
        ["SMS relies on TLS 1.0, which is deprecated", "SMS doesn't use TLS at all."]],
      ["Per NIST SP 800-63B, which authenticators are favored over SMS for MFA?",
        ["App-based or hardware authenticators", "Authenticator apps and hardware keys aren't exposed to SIM-swap or cellular interception."],
        ["Email-based codes sent to the same device", "Email to the same device is neither a separate channel nor a strong one."],
        ["Security questions", "Knowledge questions are guessable and are not a second factor of a different type."],
        ["Longer SMS codes", "A longer code doesn't fix the channel's interception and SIM-swap weaknesses."]],
      ["What determines the value of an out-of-band channel used to confirm an action?",
        ["Being truly separate and hard to compromise", "A second path only helps if an attacker who controls the first path can't also control or intercept the second."],
        ["Being faster than the primary channel", "Speed doesn't add assurance."],
        ["Using the same device as the primary login", "Sharing a device weakens the separation."],
        ["Being encrypted with the same key as the primary session", "Sharing keys ties the two channels together, which defeats the purpose."]],
      ["An attacker convinces a mobile carrier to move a victim's phone number to the attacker's SIM card, then logs into the victim's bank. Which MFA weakness was exploited?",
        ["SMS-based codes are vulnerable to SIM-swap", "Once the number is ported, SMS codes go to the attacker. App-based or hardware authenticators aren't tied to the phone number."],
        ["Hardware security keys can be cloned remotely", "Hardware keys aren't affected by number porting."],
        ["TOTP authenticator apps send codes over SMS", "Authenticator apps generate codes locally without SMS."],
        ["Passwords are hashed with SHA-256", "Password storage isn't what the attacker exploited here."]]
    ],

    "Crypto principles": [
      ["A vendor advertises its \"proprietary, secret encryption algorithm\" as a selling point. Why is this a red flag?",
        ["It violates Kerckhoff's principle", "Trustworthy crypto uses open, published algorithms that survived public scrutiny. Secrecy conceals weaknesses and fails when the algorithm leaks."],
        ["Secret algorithms are always slower than open ones", "Speed isn't the issue. Trustworthiness is."],
        ["Proprietary algorithms are unable to use keys", "They can use keys. The problem is relying on the algorithm staying secret."],
        ["Nothing, as long as the key is long enough", "A hidden, unvetted algorithm can be broken regardless of key length."]],
      ["Adding one bit to a symmetric key's length has what effect on the keyspace?",
        ["It doubles the keyspace", "Keyspace is 2^(key size), so each extra bit doubles the number of possible keys and the brute-force effort."],
        ["It adds one more possible key", "Each bit doubles the count. It doesn't add one."],
        ["It squares the keyspace", "Squaring would mean doubling the number of bits."],
        ["It has no effect unless the key is longer than 128 bits", "Every added bit doubles the keyspace at any size."]],
      ["What does \"computationally infeasible\" mean?",
        ["Possible in principle but impractical in time or resources", "This is the basis of large keyspaces and one-way hashes: breaking them isn't impossible, just impractical."],
        ["Mathematically impossible under any circumstances", "Infeasible isn't impossible. Brute force would eventually work."],
        ["Only possible with a large quantum computer", "Quantum computing affects some algorithms, but that isn't the definition."],
        ["Easy for a computer, but hard for a human", "It means hard even for computers."]],
      ["How does Moore's Law relate to choosing key sizes?",
        ["Growing compute power erodes key sizes, so plan with margin", "Transistor counts double roughly every two years, so a brute-force attack that is infeasible now gets cheaper. That's why DES's 56-bit key fell and AES uses 128–256 bits."],
        ["It proves that key sizes never need to change", "It argues the opposite."],
        ["It says keyspace doubles every two years by itself", "Moore's Law is about transistors, not keyspaces."],
        ["It applies only to hashing, not to encryption", "It applies to any brute-force effort."]],
      ["Which term describes all the information moving across a network, as opposed to stored or being processed?",
        ["Data in transit", "Data in transit is protected primarily by transport encryption such as TLS, SSH, and IPsec."],
        ["Data at rest", "Data at rest is stored on disk or in a database."],
        ["Data in use", "Data in use is loaded in memory and being processed."],
        ["Data in escrow", "Escrow refers to storing keys with a third party, not a data state."]]
    ]
  }
});
