// Chapter 2 — Protecting Data at Rest: Cryptography & Passwords
addChapter({
  id: "ch2",
  number: "2",
  title: "Data at Rest, Passwords & Cryptography",
  topics: {
    "Offline attacks & the SAM": [
      ["A powered-off laptop with an unencrypted disk is stolen. It has a strong Windows login password. Why doesn't the password protect the data?",
        ["Booting another OS reads the disk without ever asking Windows", "An attacker boots Kali from USB (or images the drive) and never asks Windows for permission. Only encryption at rest protects stored bytes."],
        ["Windows stores passwords in cleartext on the disk", "They're stored as NTLM hashes in the SAM, not cleartext. The real problem is that the disk is readable at all."],
        ["Strong passwords expire once the laptop powers off", "Passwords don't expire on power-off."],
        ["The BIOS automatically resets the Windows password", "The BIOS doesn't touch Windows credentials. Booting another OS simply bypasses them."]],
      ["Which Windows registry hive stores local account password hashes?",
        ["The SAM hive", "The Security Account Manager stores local account credentials as NTLM hashes at %SystemRoot%\\System32\\config\\SAM."],
        ["The SYSTEM hive", "SYSTEM holds the boot key (SysKey) used to decrypt the SAM's contents, not the hashes themselves."],
        ["The SOFTWARE hive", "SOFTWARE holds installed application settings."],
        ["NTUSER.DAT", "NTUSER.DAT holds per-user profile settings, not password hashes."]],
      ["An attacker copies the SAM file from an offline disk but forgot the SYSTEM hive. Why is this a problem for them?",
        ["SYSTEM holds the boot key that decrypts the SAM", "The SAM's contents are encrypted with a key kept in SYSTEM. Tools like secretsdump need both hives."],
        ["The SYSTEM hive holds the plaintext passwords", "No hive holds plaintext passwords. SYSTEM holds the boot key."],
        ["The SAM can only be read while Windows is running", "The SAM is locked while Windows runs, which is why attackers take it offline."],
        ["SYSTEM records which accounts are administrators", "The key issue is decryption, not group membership."]],
      ["What does impacket-secretsdump produce when run against the SAM and SYSTEM hives?",
        ["The NTLM hash of every local account", "secretsdump extracts the stored NTLM hashes, which then feed cracking (Hashcat -m 1000) or Pass-the-Hash."],
        ["Every account's plaintext password", "It produces hashes. Recovering plaintext still requires cracking."],
        ["The BitLocker recovery key", "secretsdump targets credential stores, not BitLocker keys."],
        ["A list of open network ports", "That's port scanning (e.g., Nmap)."]],
      ["Which MITRE ATT&CK technique describes extracting password hashes from the Windows SAM database?",
        ["T1003.002, OS Credential Dumping: SAM", "This sub-technique covers dumping local account hashes from the SAM, exactly what secretsdump does."],
        ["T1110, Brute Force (password guessing)", "T1110 covers the cracking/guessing step that follows, not the dumping itself."],
        ["T1190, Exploit Public-Facing Application", "T1190 is initial access through an internet-facing app."],
        ["T1070, Indicator Removal on Host", "T1070 is about wiping logs and evidence."]],
      ["What is NTLM, as stored in the SAM?",
        ["An unsalted MD4-based hash, also used in a challenge-response protocol", "NTLM is both the hash format inside the SAM and a network authentication protocol that uses those hashes. Being fast and unsalted makes it easy to crack."],
        ["A salted, memory-hard hash similar to Argon2id", "NTLM has no salt and isn't memory-hard."],
        ["An AES-encrypted copy of the user's password", "NTLM is a hash, not reversible encryption."],
        ["The format Windows uses for full-disk encryption", "Windows FDE is BitLocker."]],
      ["Put the lost-laptop attack chain in order.",
        ["Lost device → hive extraction → fast hash → wordlist crack → plaintext", "Each link enables the next. Breaking any one (FDE, salting, slow hashing, passphrases) stops the chain."],
        ["Wordlist crack → lost device → hive extraction → fast hash → plaintext", "Cracking can't happen before the hashes are extracted."],
        ["Plaintext → hive extraction → lost device → fast hash → wordlist crack", "The plaintext credential is the end result, not the starting point."],
        ["Hive extraction → lost device → plaintext → fast hash → wordlist crack", "The device must be obtained before the hives can be extracted."]],
      ["Which single control would have stopped the offline SAM extraction from a stolen laptop before any dumping could happen?",
        ["Full-disk encryption (e.g., BitLocker with TPM + PIN)", "With FDE the attacker who boots another OS sees only ciphertext, so there are no hives to dump."],
        ["A longer, more complex Windows password", "The login is bypassed entirely when booting another OS."],
        ["Salting the NTLM hashes stored in the SAM", "Salting slows cracking after a dump, but doesn't stop the extraction."],
        ["An account lockout policy after 5 failures", "Lockout only applies to online login attempts. Offline extraction never touches it."]],
      ["\"Physical access usually equals full access.\" What is the correct countermeasure to this maxim?",
        ["Encryption at rest, so stolen bytes are ciphertext", "When the attacker controls the hardware they choose what runs. Only encryption keeps the data unreadable."],
        ["A stronger, longer Windows login password", "The login can be bypassed by booting another OS."],
        ["A BIOS splash screen warning against theft", "A warning doesn't stop anyone."],
        ["Disabling USB ports in the Windows settings", "Windows settings don't apply when the attacker removes the drive or boots elsewhere."]]
    ],

    "Hashing vs. encryption": [
      ["Why should passwords be hashed rather than encrypted?",
        ["The system never needs the original password back", "Encryption is reversible by design. Anyone with the key could recover every password. A one-way hash avoids keeping recoverable passwords."],
        ["Hashing is reversible, so passwords can be recovered", "Hashing is one-way, and that's the point."],
        ["Encryption can't handle special characters", "Encryption handles any bytes. The issue is reversibility."],
        ["Hashes are always longer than encrypted values", "Length is irrelevant to the choice."]],
      ["Which task is encryption (not hashing) the right tool for?",
        ["Protecting a customer file that must be read back later", "Encryption is reversible with the key, which is what data at rest that must be read again requires."],
        ["Storing user password verifiers", "Passwords should be hashed with a slow, salted function."],
        ["Detecting whether a downloaded file was altered", "Integrity checking uses a hash (or HMAC/signature)."],
        ["Generating a fingerprint for an antivirus signature", "AV signatures are hashes."]],
      ["A certification exam answer says \"store passwords as SHA-256 hashes.\" Why is this wrong?",
        ["It's fast; passwords need a slow, salted algorithm", "Fast hashes let attackers test billions of guesses per second. Password hashing must be deliberately expensive and salted."],
        ["SHA-256 is reversible with the right key", "SHA-256 is one-way. Its weakness for passwords is speed."],
        ["SHA-256 produces variable-length output", "SHA-256 always outputs 256 bits."],
        ["SHA-256 has been banned outright by NIST", "SHA-256 is fine for integrity. It's just the wrong tool for passwords."]],
      ["How does traditional antivirus primarily detect malware, and what is its weakness?",
        ["Hash matching; polymorphic variants change the hash", "Exact-match signatures can't keep up with near-infinite variants, which is why behavior-based layered defense exists."],
        ["Encrypting every file; weak keys let malware in", "AV doesn't encrypt files."],
        ["Checking digital signatures from malware authors", "Malware authors don't sign their code for AV."],
        ["Decrypting network traffic; TLS defeats it", "That describes TLS inspection, not file-based antivirus."]]
    ],

    "Salts, peppers & slow hashing": [
      ["A system stores passwords as unsalted SHA-256. What are its two distinct weaknesses and the fix for each?",
        ["No salt (fix: per-password salt); too fast (fix: slow work-factor hash)", "Salting defeats precomputation and reuse detection. A slow, tunable hash like Argon2id, bcrypt, or PBKDF2 defeats high-speed guessing."],
        ["Too short (fix: switch to SHA-512); too old (fix: switch to MD5)", "MD5 is older and weaker, and SHA-512 is still fast and unsalted."],
        ["Reversible (fix: encrypt instead); public (fix: keep algorithm secret)", "SHA-256 isn't reversible, and obscurity isn't a fix."],
        ["No pepper (fix: add a pepper); no TLS (fix: serve over HTTPS)", "A pepper supplements but doesn't replace salting, and TLS protects transit, not storage."]],
      ["Two users both choose \"Summer2024!\". With a properly salted hash, what will their stored hashes look like?",
        ["Different, because each gets a unique salt", "Unique salts make identical passwords hash differently, hiding reuse and defeating precomputed tables."],
        ["Identical, because the passwords are the same", "That's the unsalted behavior that leaks reuse."],
        ["Identical, but each one stored encrypted", "Salting changes the hash input, so the outputs differ."],
        ["Blank, since duplicate passwords are rejected", "Systems don't need to reject duplicates when salting is used."]],
      ["Which statement about salts is correct?",
        ["Unique per password, random, and not secret", "A salt's job is uniqueness, not concealment. Best practice is at least 16 random bytes from a CSPRNG, never reused."],
        ["Salts must be kept secret inside an HSM", "That describes a pepper."],
        ["One salt should be shared across all users", "A shared value is a pepper. Salts must be unique."],
        ["Salts replace the need for slow hashing", "Salts stop precomputation, not fast guessing. You need both."]],
      ["How does a pepper differ from a salt?",
        ["It's one shared secret, stored apart from the database", "If only the database leaks, the attacker lacks the pepper and can't start cracking. It supplements salting and never replaces it."],
        ["It's unique per user and stored next to the hash", "That describes a salt."],
        ["It replaces the need for a salt entirely", "A pepper supplements salting; it is never a replacement."],
        ["It's the number of hashing iterations used", "That's the work factor."]],
      ["An attacker steals only the password database. The application used salted Argon2id plus a pepper stored in an HSM. What is the attacker's situation?",
        ["They can't start cracking without the pepper", "A pepper stored separately means a database-only leak is insufficient to test guesses."],
        ["They can read passwords because Argon2id is reversible", "Argon2id is a one-way hash."],
        ["They can use rainbow tables because salts are public", "Salts make precomputed tables useless even though they're public."],
        ["They can crack everything instantly with a GPU", "Argon2id is memory-hard and slow, and the pepper is missing anyway."]],
      ["What does the \"work factor\" in a password hashing function control?",
        ["How costly each hash is (iterations, CPU, or memory)", "Legitimate logins barely notice a fraction of a second, but an attacker making billions of guesses is slowed enormously."],
        ["The length of the random salt that is generated", "Salt length is a separate parameter."],
        ["How many users are allowed to share a password", "The work factor has nothing to do with sharing."],
        ["The encryption key used to protect the password", "Password hashing has no decryption key."]],
      ["If each password guess costs 100 ms instead of 100 ns, how much slower is the attacker's guessing rate?",
        ["About a million times slower", "100 ms ÷ 100 ns = 10⁶. Raising cost per guess is one of the defender's two levers, alongside entropy."],
        ["About a thousand times slower", "100 ms is 100,000,000 ns, so the ratio is 10⁶, not 10³."],
        ["About twice as slow", "The difference spans six orders of magnitude."],
        ["No slower, since GPUs ignore the work factor", "The work factor applies to every guess, on any hardware."]],
      ["Why do you need both salting and slow hashing?",
        ["They stop different attacks: precomputation vs. fast guessing", "A salted-but-fast hash is still crackable by brute force. A slow-but-unsalted hash still leaks reuse and is rainbow-table-vulnerable."],
        ["Salting makes the hash slow; slow hashing makes it unique", "This swaps their roles."],
        ["Either one alone is sufficient on its own", "Each addresses a different attack, so neither alone is enough."],
        ["Salting encrypts the hash; slow hashing signs it", "Neither one encrypts or signs."]],
      ["Which password hashing function won the 2015 Password Hashing Competition and is memory-hard?",
        ["Argon2 (Argon2id recommended)", "Argon2id forces large RAM per guess, blunting cheap GPU/ASIC parallelism. OWASP lists it first."],
        ["bcrypt, based on Blowfish", "bcrypt is long-trusted and tunable, but not memory-hard, and predates the competition."],
        ["PBKDF2, from NIST SP 800-132", "PBKDF2 is the FIPS-friendly choice (SP 800-132), but it isn't memory-hard."],
        ["SHA-256, from the SHA-2 family", "SHA-256 is a fast general-purpose hash, not a password hashing function."]],
      ["A government contractor must use a password hashing algorithm that fits FIPS validation requirements. Which is the appropriate pick?",
        ["PBKDF2 (specified in NIST SP 800-132)", "PBKDF2 is the FIPS-approved key derivation function. Since it isn't memory-hard, it needs a high iteration count."],
        ["Argon2id, the competition winner", "Argon2id is generally the strongest choice, but it is not the FIPS-approved KDF."],
        ["MD5 with a per-user salt", "MD5 is fast, broken, and not appropriate for passwords."],
        ["NTLM, as used by Windows", "NTLM is an unsalted MD4 hash and highly crackable."]],
      ["What is a known limitation of bcrypt?",
        ["It isn't memory-hard and truncates long inputs (~72 bytes)", "bcrypt is still a reasonable choice for many systems, but long passphrases may be truncated and it doesn't resist GPUs like Argon2."],
        ["It cannot use a salt of any kind", "bcrypt includes a salt."],
        ["It has no tunable cost factor at all", "bcrypt has a tunable cost factor."],
        ["It is reversible if the key is known", "bcrypt is one-way."]],
      ["What is the OWASP Password Storage Cheat Sheet's preferred order of algorithms?",
        ["Argon2id → scrypt → bcrypt → PBKDF2", "OWASP gives the practitioner-level ordering. Argon2id comes first as memory-hard, with PBKDF2 for FIPS needs."],
        ["SHA-256 → SHA-1 → MD5 → NTLM", "These are fast hashes and inappropriate for passwords."],
        ["PBKDF2 → bcrypt → MD5 → Argon2id", "MD5 should never be on the list, and Argon2id is first, not last."],
        ["bcrypt → SHA-512 → scrypt → AES", "SHA-512 is fast and AES is encryption, so neither belongs."]]
    ],

    "Password cracking": [
      ["How does password cracking actually work?",
        ["Guess, hash each guess, and compare to the target", "Attackers never reverse the hash. They re-derive it from guesses, so the defender's goal is to make each guess expensive."],
        ["Mathematically reverse the hash function", "Hashes are one-way. Cracking works by guessing."],
        ["Decrypt the hash with the system's private key", "Password hashes have no decryption key."],
        ["Read the plaintext out of the stored salt", "Salts are random values, not passwords."]],
      ["A cracker applies transformations to dictionary words, such as capitalizing, appending a year, and swapping a→@, turning \"shopquest\" into \"ShopQuest2024!\". Which attack is this?",
        ["Rule-based (mangling) attack", "Rules capture the predictable ways people \"complexify\" a base word."],
        ["Pure brute force", "Brute force tries every combination with no dictionary."],
        ["Rainbow table lookup", "Rainbow tables are precomputed lookups that don't apply rules."],
        ["Pass-the-hash", "Pass-the-hash reuses a hash directly without cracking it."]],
      ["Which attack uses precomputed lookup tables to reverse unsalted hashes almost instantly?",
        ["Rainbow tables", "Rainbow tables trade memory for time. A unique per-password salt defeats them entirely."],
        ["Hybrid attack", "Hybrid combines wordlists with brute-forced prefixes or suffixes."],
        ["Dictionary attack", "A dictionary attack hashes wordlist entries at attack time and doesn't use precomputed tables."],
        ["Side-channel attack", "Side channels attack an implementation via timing or power."]],
      ["An attacker tries each word in a wordlist with a brute-forced 4-digit number appended (e.g., \"dragon0000\" to \"dragon9999\"). What kind of attack is this?",
        ["Hybrid attack", "A hybrid attack combines a wordlist with brute-forced prefixes or suffixes."],
        ["Pure dictionary attack", "A pure dictionary attack doesn't add brute-forced parts."],
        ["Rainbow table attack", "That's a precomputed lookup."],
        ["Chosen-plaintext attack", "That's a cryptanalysis model against ciphers."]],
      ["Which two factors determine how long it takes to crack a password hash?",
        ["The password's entropy and the cost of each guess", "Defenders control both: passphrases raise entropy, and slow hashes raise cost per guess."],
        ["The username's length and the server's location", "Neither factor affects cracking time."],
        ["The TLS version and the certificate's expiry", "These concern data in transit, not cracking stored hashes."],
        ["The number of salts and the number of peppers", "Salts affect precomputation, but the core factors are entropy and speed."]],
      ["What tool, run on GPUs, cracks hashes by guessing, hashing, and comparing (e.g., mode -m 1000 for NTLM)?",
        ["Hashcat", "Hashcat is a fast, open-source password recovery tool. GPU acceleration makes fast hashes fall quickly."],
        ["Wireshark", "Wireshark captures and analyzes packets."],
        ["Nmap", "Nmap scans ports and services."],
        ["certUtil", "certUtil can compute file hashes but doesn't crack them."]],
      ["Which ATT&CK technique covers the password-cracking step, including dictionary and rule-based variants?",
        ["T1110, Brute Force", "T1110 tracks guessing attacks, including password cracking."],
        ["T1003.002, SAM credential dumping", "That's the extraction step before cracking."],
        ["T1040, Network Sniffing", "That's capturing traffic."],
        ["T1595.001, Active Scanning", "That's reconnaissance scanning."]]
    ],

    "Entropy & password policy": [
      ["Per NIST SP 800-63B, why are long passphrases preferred over short, forced-complexity passwords?",
        ["Length multiplies the keyspace far more than symbols do", "SP 800-63B favors length and breached-password screening over composition rules, which push users toward predictable patterns."],
        ["Complexity rules are too hard to program correctly", "The reason is entropy and human behavior, not implementation difficulty."],
        ["Long passwords are exempt from being hashed", "Every password must be hashed."],
        ["Symbols are no longer allowed in modern systems", "SP 800-63B says to allow the full character range, including spaces."]],
      ["Which is a NIST SP 800-63B recommendation?",
        ["Screen new passwords against breached and common lists", "Blocking breached and common choices like \"ShopQuest2024!\" removes the passwords attackers try first."],
        ["Force all users to change passwords every 60 days", "SP 800-63B says not to force periodic expiration without cause."],
        ["Require an uppercase letter, a number, and a symbol", "SP 800-63B says not to impose arbitrary composition rules."],
        ["Limit passwords to a maximum of 16 characters", "It says to allow long passwords (at least 64 characters)."]],
      ["Why does SP 800-63B advise against forced periodic password expiration?",
        ["It pushes users toward predictable increments", "Forced changes produce small, guessable increments. Change passwords when there's evidence of compromise instead."],
        ["Expired passwords can no longer be hashed", "Hashing is unaffected by expiration."],
        ["It increases password entropy far too much", "It actually tends to reduce real entropy."],
        ["Users would be forced to use passphrases", "Passphrases are encouraged, not a problem."]],
      ["A word is chosen uniformly at random from a list of 2,048 words. How many bits of entropy does that one word provide?",
        ["11 bits", "Entropy is log₂(N), and 2¹¹ = 2,048. Four such random words give 44 bits."],
        ["2,048 bits", "Entropy is the logarithm of the number of choices, not the count itself."],
        ["8 bits", "2⁸ = 256, which is too small."],
        ["1 bit", "One bit would be a choice between only two options."]],
      ["A user picks \"P@ssw0rd!\". It is 9 characters with uppercase, symbol, and digit. Why does it have very little real entropy?",
        ["It's a predictable, human-chosen pattern, not random", "Attackers exploit predictability. Dictionary and rule-based attacks find this almost immediately."],
        ["It is too short to be hashed by most systems", "Any length can be hashed."],
        ["Using symbols actually reduces a password's entropy", "Symbols don't reduce entropy. The predictable choice does."],
        ["Only multi-word passphrases can have entropy", "Any secret has entropy. This one just has very little."]],
      ["Which is more resistant to cracking: \"correct-harbor-anchor-velvet\" or \"ShopQuest2024!\"?",
        ["The random four-word passphrase", "The passphrase is easy to recall and astronomically harder to crack. The themed password is in wordlists or a few rules away."],
        ["ShopQuest2024!, because it uses more character types", "Character variety adds little when the base is predictable."],
        ["They are equal, since both exceed 12 characters", "Length only helps if the choice is unpredictable."],
        ["Neither, since all passwords crack instantly", "Strong passphrases combined with slow hashing resist cracking."]],
      ["What does \"bits of entropy\" measure?",
        ["How many times you'd halve the search space to find it", "A value chosen uniformly from N possibilities has log₂(N) bits. Each bit doubles the attacker's work."],
        ["The number of characters in a password", "Character count isn't entropy. Predictable long passwords have little."],
        ["The fixed size of the stored hash output", "Hash size is fixed and unrelated to password strength."],
        ["The number of failed login attempts allowed", "That's a lockout setting."]]
    ],

    "Classical ciphers": [
      ["Using a Caesar cipher with shift K = 3, what does the letter X encrypt to?",
        ["A", "C = (P + K) mod 26. X is 23, so 23 + 3 = 26, and 26 mod 26 = 0, which is A. The modulo creates the wraparound."],
        ["Z", "X + 2 = Z. With a shift of 3 you wrap past Z to A."],
        ["[", "The mod 26 operation keeps the result inside the alphabet."],
        ["U", "U is X shifted backward by 3, which is decryption, not encryption."]],
      ["What is the purpose of the modulo operation in the Caesar formula C = (P + K) mod 26?",
        ["It wraps past Z back around to A", "Modulo is the remainder after division, which keeps every result within the 26 letters."],
        ["It hides the shift key from attackers", "Modulo doesn't hide anything. The Caesar keyspace is only 26."],
        ["It adds randomness to each letter", "Caesar is fully deterministic."],
        ["It converts each letter into binary", "It operates on letter positions 0–25."]],
      ["What is the difference between a substitution cipher and a transposition cipher?",
        ["Substitution replaces symbols; transposition reorders them", "These are the two primitive cipher operations. Modern block ciphers combine both over many rounds."],
        ["Substitution reorders symbols; transposition replaces them", "This reverses the definitions."],
        ["Substitution uses public keys; transposition uses private keys", "Both are classical symmetric techniques."],
        ["They are the same operation under different names", "They're distinct operations."]],
      ["A simple substitution cipher maps each letter to an arbitrary other letter. Its keyspace is far larger than Caesar's 26 shifts, yet it's easily broken. Why?",
        ["Letter frequencies survive, enabling frequency analysis", "The relationships between letters persist. An analyst bootstraps from the most common ciphertext symbol."],
        ["Its keyspace is actually smaller than Caesar's", "It's vastly larger (26! keys)."],
        ["It relies on XOR, which is trivially reversible", "Classical substitution doesn't use XOR."],
        ["It encrypts each letter with a different key", "That describes Vigenère, which flattens frequencies."]],
      ["Encrypting HELLO with the Vigenère key KEY turns the two L's into different ciphertext letters (J then V). What property causes this?",
        ["It's polyalphabetic: each position uses a different shift", "Vigenère nests many Caesar shifts under a repeating keyword, so the same plaintext letter can encrypt differently."],
        ["It's a transposition cipher that reorders the letters", "Vigenère substitutes letters. It doesn't reorder them."],
        ["It applies a one-way hash to each letter", "Vigenère is reversible encryption, not hashing."],
        ["It switches to a new alphabet for every message", "The shift changes per letter position based on the keyword."]],
      ["How do you use a tabula recta to encrypt a letter with Vigenère?",
        ["Plaintext letter on top, key letter on the left; read the intersection", "The tabula recta has 26 alphabets, each shifted one place further than the last."],
        ["Write the message in a grid and read the columns in keyword order", "That's columnar transposition."],
        ["Shift every letter forward by the same fixed amount", "That's a Caesar cipher."],
        ["XOR the letter with the binary value of the key letter", "That's a modern stream-cipher idea, not the tabula recta method."]],
      ["How does a columnar transposition cipher work?",
        ["Write it in a grid under a keyword; read columns in keyword order", "Letters are kept but rearranged. Doing it twice with two keywords is the U.S. Army's double transposition."],
        ["Replace each letter with the letter K positions later", "That's Caesar substitution."],
        ["Encrypt each letter under a different tabula recta row", "That's Vigenère."],
        ["XOR each byte of the message with a one-time pad", "That's a one-time pad or stream cipher."]],
      ["Why can a double transposition still eventually be broken by a patient analyst?",
        ["All original letters remain, so frequencies still match", "Transposition only scrambles order, and the frequency of E, T, A… is unchanged. Modern ciphers combine substitution and transposition over many rounds."],
        ["It only uses a small 26-key keyspace", "It needs two keywords, which is a much larger keyspace."],
        ["The keywords are transmitted in cleartext", "Nothing in the cipher's design sends keys in the clear."],
        ["It reveals the key in its first block", "There are no blocks or key leakage in this design."]],
      ["What is XOR, and why is it central to modern ciphers?",
        ["Outputs true only when inputs differ; trivially reversible", "A XOR K = C, and C XOR K = A. Applying the same key twice undoes it."],
        ["A one-way function used for hashing passwords", "XOR is fully reversible, not one-way."],
        ["Outputs true only when both inputs are true", "That's AND."],
        ["A method for exchanging keys over a public channel", "That's Diffie–Hellman."]],
      ["Which term describes the readable message that goes into a cipher, versus the scrambled output?",
        ["Plaintext (cleartext) goes in; ciphertext comes out", "A cipher is an algorithm that transforms plaintext under a key into ciphertext."],
        ["Ciphertext goes in; plaintext comes out", "That's decryption, the reverse direction."],
        ["A digest goes in; a salt comes out", "These are hashing terms."],
        ["The keyspace goes in; the key size comes out", "These describe keys, not messages."]],
      ["ROT13 is applied twice to a message. What is the result?",
        ["The original plaintext", "ROT13 rotates by 13 of 26 letters, so applying it twice is a full 26-letter rotation back to the start. It offers no real security."],
        ["Ciphertext rotated by 26 extra characters", "A 26-character rotation is the identity, which gives back the original."],
        ["A hash of the original message", "ROT13 is a reversible substitution, not a hash."],
        ["A Vigenère ciphertext with key \"ROT\"", "ROT13 is a single fixed Caesar shift."]]
    ],

    "Keyspace, brute force & quantum": [
      ["On average, how much of the keyspace must a brute-force attack search before finding the key?",
        ["About half", "Each key is equally likely to be correct, so on average the key turns up halfway through. Key size sets the time-to-break."],
        ["All of it, every time", "The full search is the worst case, not the average."],
        ["About 1%", "The expected search is 50% of the space."],
        ["The square root of the keyspace", "That's Grover's quantum speedup, or the birthday bound for collisions."]],
      ["Why is DES now considered breakable while AES-128 is not?",
        ["2⁵⁶ keys can be exhausted; 2¹²⁸ cannot", "Each extra bit doubles the keyspace. 72 more bits put AES far beyond any brute force."],
        ["AES uses a secret, unpublished algorithm", "AES is a published, open standard (FIPS 197)."],
        ["DES is an asymmetric public-key algorithm", "DES is symmetric."],
        ["DES doesn't actually use a key at all", "DES uses a 56-bit key."]],
      ["What is the difference between key size and keyspace?",
        ["Size is the length in bits; keyspace is 2^size", "A 128-bit key has a keyspace of 2¹²⁸ possible values."],
        ["They mean exactly the same thing", "One is a length; the other is a count of possibilities."],
        ["Keyspace is length in bytes; key size is in bits", "Keyspace is a number of possible keys, not a length."],
        ["Key size counts users; keyspace counts devices", "Neither term counts users or devices."]],
      ["How does Grover's algorithm affect symmetric encryption like AES?",
        ["It roughly halves effective strength; doubling key size fixes it", "Grover speeds up search to about the square root of the keyspace. AES-256 still gives ~128-bit security."],
        ["It breaks AES outright regardless of key size", "That's what Shor's algorithm does to RSA and ECC, not Grover to AES."],
        ["It has no effect at all on symmetric ciphers", "It does have an effect: it roughly halves effective strength."],
        ["It makes AES stronger against classical attacks", "Grover helps attackers, not defenders."]],
      ["Why does Shor's algorithm threaten RSA and elliptic-curve cryptography so much more than Grover threatens AES?",
        ["It solves the underlying math, so bigger keys don't help", "RSA's foundation (factoring) and ECC's foundation (discrete log) collapse on a large quantum computer. Bigger keys aren't a fix, so post-quantum algorithms are needed."],
        ["Shor brute-forces keys faster than Grover does", "Shor doesn't brute-force at all. It solves the underlying math."],
        ["RSA and ECC use shorter keys than AES does", "Key length isn't the issue."],
        ["Shor only works against hash functions", "Shor targets factoring and discrete logarithms."]],
      ["Attackers are recording encrypted traffic today, planning to decrypt it once large quantum computers exist. What is this called, and what counters it?",
        ["Harvest now, decrypt later; migrate to post-quantum crypto", "Data with a long secrecy lifetime is at risk now. NIST standardized ML-KEM (Kyber) and ML-DSA (Dilithium) in 2024."],
        ["A side-channel attack; countered by EM shielding", "Side channels exploit implementation leaks like timing or power, not future decryption."],
        ["A downgrade attack; countered by enforcing TLS 1.3", "TLS 1.3 alone doesn't address quantum threats to key exchange."],
        ["A rainbow table attack; countered by salting", "Rainbow tables target password hashes."]],
      ["Which NIST post-quantum standard is used for key exchange (key encapsulation)?",
        ["ML-KEM (Kyber)", "ML-KEM is the post-quantum key encapsulation mechanism standardized in 2024."],
        ["ML-DSA (Dilithium)", "ML-DSA is for digital signatures."],
        ["PBKDF2", "PBKDF2 is a password-based key derivation function."],
        ["AES-256", "AES is symmetric and already quantum-resistant at 256 bits. It isn't a PQC key exchange."]]
    ],

    "Cryptanalysis & hash properties": [
      ["An analyst has only intercepted encrypted messages and nothing else, then uses letter frequencies to break them. Which attack model is this?",
        ["Ciphertext-only", "With only ciphertext available, frequency analysis is the classic technique."],
        ["Known-plaintext", "That requires seeing some plaintext paired with its ciphertext."],
        ["Chosen-plaintext", "That requires the ability to submit chosen plaintext for encryption."],
        ["Chosen-ciphertext", "That requires the ability to get chosen ciphertexts decrypted."]],
      ["An attacker can submit plaintext of their choosing to a system and observe the resulting ciphertext. Which model is this?",
        ["Chosen-plaintext", "The attacker picks the inputs to encrypt and studies the outputs."],
        ["Known-plaintext", "Known-plaintext means seeing plaintext/ciphertext pairs without choosing them."],
        ["Ciphertext-only", "The attacker would have only ciphertext."],
        ["Chosen-ciphertext", "That's choosing ciphertexts to be decrypted."]],
      ["An attacker obtained some captured messages along with their decrypted contents but could not choose which messages. Which model is this?",
        ["Known-plaintext", "The attacker sees matching plaintext/ciphertext pairs but can't pick them."],
        ["Chosen-plaintext", "Choosing the plaintext is the defining feature of chosen-plaintext, and that wasn't possible here."],
        ["Ciphertext-only", "They have some plaintext too, so this isn't ciphertext-only."],
        ["Side-channel", "Side channels exploit timing or power, not message pairs."]],
      ["An attacker measures how long a smart card takes to perform decryptions and recovers the key from timing differences. What kind of attack is this?",
        ["Side-channel attack", "Side channels (timing, power draw, EM leakage) attack the implementation rather than the math."],
        ["Chosen-ciphertext attack", "That's a mathematical model about chosen inputs, not physical leakage."],
        ["Birthday attack", "Birthday attacks look for hash collisions."],
        ["Frequency analysis", "That's breaking classical ciphers by letter frequency."]],
      ["You run certUtil -hashfile report.txt sha256, capitalize a single letter in the file, and run it again. What happens to the digest?",
        ["Essentially every hex digit changes, which is the avalanche effect", "A tiny input change flips about half the output bits, making the digest a tamper-evident fingerprint."],
        ["Only one hex digit changes", "Good hashes don't change gradually."],
        ["The digest stays the same because the length didn't change", "Any content change changes the digest."],
        ["The digest gets longer", "SHA-256 output is always 256 bits (64 hex characters)."]],
      ["How long is a SHA-256 digest, and how long is an MD5 digest?",
        ["256 bits (64 hex characters) and 128 bits", "Hash outputs are fixed length regardless of input size."],
        ["Variable, depending on the input size", "Hash output is always fixed length."],
        ["128 bits and 256 bits", "This reverses them."],
        ["64 bits and 32 bits", "These are far too short."]],
      ["Per the birthday paradox, how much collision resistance does SHA-256 actually provide?",
        ["About 128 bits", "An n-bit hash gives n/2 bits of collision resistance. Finding some matching pair is far easier than hitting a chosen target."],
        ["The full 256 bits", "256 bits applies to hitting a specific target (preimage), not to finding any collision."],
        ["About 64 bits", "That would be a 128-bit hash's collision resistance."],
        ["Zero, since SHA-256 collisions are trivial", "SHA-256 collisions are computationally infeasible."]],
      ["In a room of 23 people, there's about a 50% chance two share a birthday, but matching your specific birthday takes about 253 people. What security idea does this illustrate?",
        ["Finding any collision is easier than a specific one", "This is the birthday paradox. It's why collision resistance is only half the hash's bit length."],
        ["Larger keyspaces are easier to brute-force", "Larger keyspaces are harder to search."],
        ["Salts are unnecessary for unique passwords", "That's unrelated, and salts are always needed."],
        ["Hashes become reversible with enough samples", "Hashes stay one-way. This is about collisions."]],
      ["Polymorphic malware changes its code with every copy. Why does this defeat hash-based antivirus signatures?",
        ["Any byte change produces a completely different hash", "Because of the avalanche effect, defenders would need a new signature per variant, a race they can't win."],
        ["It encrypts the antivirus signature database", "It changes itself, not the AV database."],
        ["Antivirus can't compute hashes of executables", "AV can hash any file."],
        ["It reuses the same hash as trusted system files", "Engineering a specific hash match is computationally infeasible."]]
    ],

    "Encryption at rest & key management": [
      ["Which level of encryption at rest makes a stolen laptop's entire volume unreadable until the key unlocks it at boot?",
        ["Full-disk encryption (BitLocker, LUKS, FileVault)", "FDE encrypts the whole volume. Booting from a Kali USB yields only ciphertext."],
        ["File/folder encryption (e.g., Windows EFS)", "File encryption protects selected items and leaves the rest of the disk exposed."],
        ["Column-level encryption in the database", "Column encryption protects specific database fields, not the whole disk."],
        ["TLS 1.3 on all network connections", "TLS protects data in transit."]],
      ["A DBA has broad database access, but card numbers must stay protected even from them. Which control fits?",
        ["Column/field-level encryption", "Field-level encryption protects specific sensitive columns even from users with broad database access."],
        ["Transparent Data Encryption (TDE) alone", "TDE encrypts files on disk, but authorized database users still see plaintext."],
        ["Full-disk encryption", "FDE protects against disk theft, not against logged-in users."],
        ["Salting the card numbers", "Salting applies to hashing, and card numbers must be recoverable."]],
      ["What does a TPM do for full-disk encryption?",
        ["Seals the disk key to the machine and its verified boot state", "The Trusted Platform Module is a tamper-resistant chip that ties the key to the hardware and boot integrity."],
        ["Stores users' passwords in plaintext for recovery", "TPMs don't store plaintext passwords."],
        ["Encrypts network traffic leaving the laptop", "That's TLS or IPsec."],
        ["Replaces the need for any disk encryption", "A TPM protects encryption keys. It doesn't replace encryption."]],
      ["A laptop uses BitLocker with TPM-only auto-unlock. It's stolen while powered on and at the login screen. What gap exists, and how is it closed?",
        ["TPM-only unlocks automatically; add a pre-boot PIN", "TPM-only defeats drive removal, but the key releases automatically at boot. A PIN or passphrase adds a factor the thief lacks."],
        ["No gap; TPM-only auto-unlock is complete protection", "Auto-unlock means the key is available without the user."],
        ["Switch from FDE to file encryption instead", "That weakens coverage rather than closing the gap."],
        ["Disable the TPM so the key isn't stored", "Removing the TPM removes protection instead of adding it."]],
      ["What is a hardware security module (HSM)?",
        ["A dedicated device that generates and guards keys", "HSMs (and KMS services) centralize key management in larger environments."],
        ["A firewall that filters encrypted traffic", "That's a TLS-inspection proxy or firewall."],
        ["A chip that stores only BIOS settings", "That describes CMOS. HSMs protect keys."],
        ["A software library for hashing passwords", "HSMs are hardware key guardians."]],
      ["\"Encryption is only as strong as its key management.\" Which scenario shows this?",
        ["AES-256 data with its key in a plaintext file beside it", "Anyone who steals the server gets both the ciphertext and the key, so the encryption adds nothing."],
        ["AES-256 data with its keys held in an HSM", "This is good key management."],
        ["A laptop using BitLocker with TPM + PIN", "This is strong key protection."],
        ["Passwords hashed with salted Argon2id", "Hashing has no decryption key to mismanage."]],
      ["What does FIPS 140-3 certify?",
        ["Cryptographic modules (hardware or software)", "FIPS 140-3 replaces 140-2 and validates crypto modules for government use."],
        ["The AES algorithm itself", "AES is defined in FIPS 197."],
        ["The impact levels of information systems", "That's FIPS 199."],
        ["Minimum security requirements for federal systems", "That's FIPS 200."]],
      ["Which FIPS standard categorizes information systems as low, moderate, or high impact based on loss of confidentiality, integrity, or availability?",
        ["FIPS 199", "FIPS 199 is foundational to the NIST RMF and is paired with FIPS 200's minimum requirements."],
        ["FIPS 197", "FIPS 197 defines AES."],
        ["FIPS 140-3", "FIPS 140-3 certifies cryptographic modules."],
        ["FIPS 200", "FIPS 200 sets minimum requirements that build on FIPS 199's categories."]],
      ["Which NIST publication gives canonical guidance on storage encryption for end-user devices like laptops?",
        ["SP 800-111", "SP 800-111 covers full-disk and file encryption choices for end-user devices."],
        ["SP 800-88", "SP 800-88 covers media sanitization."],
        ["SP 800-63B", "SP 800-63B covers digital identity and passwords."],
        ["SP 800-132", "SP 800-132 covers PBKDF2."]]
    ],

    "Media sanitization": [
      ["Which NIST publication governs media sanitization?",
        ["SP 800-88", "SP 800-88 defines Clear, Purge, and Destroy, including cryptographic erase."],
        ["SP 800-111", "SP 800-111 covers device storage encryption."],
        ["SP 800-63B", "SP 800-63B covers authentication."],
        ["SP 800-175B", "SP 800-175B covers selecting cryptographic mechanisms."]],
      ["What is cryptographic erase, and what's its prerequisite?",
        ["Destroying the key; only works if data was encrypted", "It's a fast, scalable Purge technique. There's nothing to erase cryptographically if the data was never encrypted."],
        ["Overwriting with zeros; requires a magnetic drive", "Overwriting is Clear and isn't key-based."],
        ["Shredding the drive; requires an industrial shredder", "Shredding is Destroy."],
        ["Re-encrypting the data; requires two separate keys", "Re-encrypting doesn't sanitize."]],
      ["Under SP 800-88, which sanitization level uses a logical overwrite that resists casual recovery?",
        ["Clear", "Clear is the lowest level. It protects against simple, non-lab recovery."],
        ["Purge", "Purge resists laboratory attacks (e.g., cryptographic erase)."],
        ["Destroy", "Destroy physically ruins the media."],
        ["Archive", "Archive isn't an SP 800-88 sanitization level."]],
      ["Drives held highly classified data and must never be reused. Which SP 800-88 level applies?",
        ["Destroy", "Destroy is for media that must never be reused."],
        ["Clear", "Clear only resists casual recovery and leaves the drive reusable."],
        ["Purge", "Purge resists lab recovery but leaves media potentially reusable."],
        ["A quick format of the drive", "A quick format isn't sanitization."]],
      ["Which sanitization level does cryptographic erase belong to?",
        ["Purge", "Cryptographic erase resists laboratory recovery, which puts it at the Purge level."],
        ["Clear", "Clear is a simple logical overwrite."],
        ["Destroy", "Destroy is physical destruction."],
        ["None; it isn't a recognized method", "SP 800-88 explicitly recognizes it."]]
    ],

    "Data states, classification & roles": [
      ["A lost laptop held customer data saved on its SSD. Which data state was that data in?",
        ["At rest", "Data stored on disk, in a database, or on backup tape is at rest and is protected by storage encryption and access controls."],
        ["In transit", "In transit means moving across a network."],
        ["In use", "In use means loaded in memory and being processed."],
        ["In escrow", "That's not one of the three data states."]],
      ["Which data state is hardest to protect, and what addresses it?",
        ["In use; secure enclaves and confidential computing", "Data being processed must be decrypted in memory, which makes it hardest to protect."],
        ["At rest; protected with TLS", "TLS protects data in transit."],
        ["In transit; protected with full-disk encryption", "FDE protects data at rest."],
        ["At rest; protected by hashing the files", "Hashing isn't a general data-at-rest protection."]],
      ["What is the purpose of data classification?",
        ["Labeling data by sensitivity so handling is consistent", "Classification is the policy decision that drives technical controls, such as requiring encryption for Restricted data."],
        ["Encrypting all data with the same key", "Classification decides protections. It isn't encryption."],
        ["Deleting any data older than a year", "That's retention or disposal."],
        ["Sorting files alphabetically by owner", "Classification is about sensitivity."]],
      ["Who is accountable for a data asset and sets its classification?",
        ["The data owner, typically a business leader", "The owner is accountable and decides classification and required controls."],
        ["The data custodian, typically IT", "The custodian (usually IT) implements the controls the owner requires."],
        ["The data processor, often a third party", "The processor handles data on the owner's behalf, often a third party."],
        ["The data subject, the person described", "The subject is the individual the data describes."]],
      ["An IT team configures backups and encryption according to the business owner's requirements. What role is IT playing?",
        ["Data custodian", "Custodians implement and maintain the controls the owner requires."],
        ["Data owner", "The owner sets requirements. IT implements them here."],
        ["Data subject", "Subjects are the people the data is about."],
        ["Data controller", "That's a privacy-law term. This chapter's roles name IT as the custodian."]],
      ["A payroll company processes employee data on behalf of a client business. What role does the payroll company play?",
        ["Data processor", "A processor handles data on behalf of the owner, often as a third party."],
        ["Data owner", "The client business owns the data."],
        ["Data subject", "The employees are the subjects."],
        ["Data custodian", "Custodian is the internal IT implementer role."]],
      ["A lost device held unencrypted customer PII. Why does this become a reportable breach rather than just lost hardware?",
        ["Without encryption, the data itself is exposed", "Handling covers the full lifecycle. A lost device is an unplanned end-of-life event, and encryption is what keeps it from being a breach."],
        ["All lost hardware is automatically a reportable breach", "With encryption, a loss usually isn't a data breach."],
        ["Because the laptop's warranty had expired", "Warranty status is irrelevant."],
        ["Because the device was over three years old", "Age is irrelevant."]],
      ["An attacker subtly tampers with the dataset used to train a fraud-detection model so it learns to ignore their transactions. What attack is this?",
        ["Data poisoning of the training set", "Poisoning corrupts what the model learns rather than attacking the running system. Training data and model weights need classification and integrity controls."],
        ["Prompt injection against the model", "Prompt injection manipulates a running model's input instructions."],
        ["A rainbow table attack on the data", "That targets password hashes."],
        ["Cryptographic erase of the dataset", "That's a sanitization method."]],
      ["A model is trained on customer PII. Which privacy-preserving controls are recommended?",
        ["Differential privacy and data masking", "These reduce how much individual PII a model can memorize or reveal."],
        ["Removing all encryption to speed up training", "That weakens protection."],
        ["Publishing the training data for transparency", "That exposes PII."],
        ["Using MD5 to hash the model weights", "Weak hashing isn't a privacy control."]]
    ],

    "Small-business defenses & standards": [
      ["A small office wants the most impactful low-cost protections. Which set matches the chapter's recommendations?",
        ["Password manager, MFA, built-in FDE, and screen locks", "Unique strong passwords, MFA, FDE (BitLocker/FileVault), and screen locks address the most common failures cheaply."],
        ["Forced 30-day password changes and complexity rules", "SP 800-63B discourages both."],
        ["A secret, proprietary encryption algorithm", "That violates Kerckhoff's principle."],
        ["All passwords stored in one shared spreadsheet", "That puts every credential in one plaintext file."]],
      ["Which NIST SP covers selecting approved cryptographic algorithms and using cryptography correctly?",
        ["SP 800-175B", "SP 800-175B provides guidance on cryptographic mechanisms."],
        ["SP 800-88", "SP 800-88 covers sanitization."],
        ["SP 800-41", "SP 800-41 covers firewalls."],
        ["SP 800-115", "SP 800-115 covers security testing."]],
      ["In the lost-laptop defense-in-depth model, which control-to-threat pairing is correct?",
        ["Salting stops precomputation", "Salts defeat rainbow tables. FDE stops the dump, slow hashing stops guessing, passphrases raise entropy, and a pepper survives a DB leak."],
        ["FDE stops fast GPU guessing", "FDE stops the offline dump, not guessing against an already-leaked hash."],
        ["A pepper stops the offline mount", "FDE stops the mount. A pepper protects a leaked database."],
        ["Passphrases stop rainbow tables", "Salts stop rainbow tables. Passphrases raise entropy."]],
      ["Designing how passwords are stored and protected primarily falls under which CISSP domain?",
        ["Domain 3: Security Architecture & Engineering", "Designing cryptographic controls (hashing, key management, TPM/HSM) is Domain 3."],
        ["Domain 2: Asset Security", "Domain 2 covers classification, handling, and data states."],
        ["Domain 6: Security Assessment & Testing", "Domain 6 is testing."],
        ["Domain 4: Communication & Network Security", "Domain 4 is networking."]]
    ]
  }
});
