// Chapter 4 — Network Monitoring & the Limits of Encryption
addChapter({
  id: "ch4",
  number: "4",
  title: "Network Monitoring & the Limits of Encryption",
  topics: {
    "Capture, flow & logs": [
      ["Rank full-packet capture, NetFlow, and host logs from most to least useful for investigating an attack over an encrypted SSH channel.",
        ["Host logs, then NetFlow, then full-packet capture", "Host logs hold the plaintext the wire hid (written after decryption). NetFlow's metadata survives encryption. FPC payload is just ciphertext, though it still has value as metadata and evidence."],
        ["Full-packet capture, then NetFlow, then host logs", "FPC payload is ciphertext here, so it's least useful for content."],
        ["NetFlow, then full-packet capture, then host logs", "Host logs are the most useful because they record the decrypted events."],
        ["All three are equally useful", "Encryption affects each source very differently."]],
      ["What is full-packet capture (FPC)?",
        ["Recording every byte of every packet to disk, as tcpdump does", "FPC has the highest fidelity and is replayable, but it's the most storage-expensive and the least useful for encrypted payloads."],
        ["A summary of who talked to whom, for how long, and how many bytes", "That's a flow record."],
        ["Records written by endpoints describing their own activity", "Those are logs."],
        ["A passive inline hardware device", "That's a network tap."]],
      ["Which monitoring source is cheap, scales to enormous networks, and survives encryption untouched because it never depended on payload?",
        ["Flow records (NetFlow/IPFIX)", "Flow summarizes conversations (endpoints, ports, bytes, duration) without contents, so encryption doesn't affect it."],
        ["Full-packet capture", "FPC is expensive and its payload is ciphertext when traffic is encrypted."],
        ["TLS-inspection proxy logs", "A proxy can't decrypt everything (e.g., SSH, pinned apps), and it isn't cheap."],
        ["Antivirus signature databases", "These aren't a network monitoring source."]],
      ["What is IPFIX?",
        ["The vendor-neutral standard form of NetFlow", "IP Flow Information Export standardizes flow records across vendors."],
        ["A file format for full packet captures", "That's pcap."],
        ["A type of intrusion prevention system", "That's an IPS."],
        ["An encrypted, append-only logging protocol", "IPFIX is about flow export."]],
      ["Why do endpoint logs often contain information that network capture of encrypted traffic cannot?",
        ["The endpoint writes logs after it decrypts and processes the traffic", "Logs capture the meaning the wire concealed, such as failed and successful logins."],
        ["Logs are encrypted with a weaker cipher", "Logs aren't a weaker-encrypted copy of the traffic."],
        ["Network capture can't see IP addresses", "Network capture does see IPs."],
        ["Logs record traffic before it's encrypted on the wire by the router", "Routers don't encrypt and decrypt application traffic. The endpoint does."]],
      ["What is the difference between payload and metadata?",
        ["Payload is the content; metadata is IPs, ports, timing, and sizes", "Encryption hides the payload, but metadata stays visible because routing needs it."],
        ["Payload is the IP header; metadata is the content", "This reverses them."],
        ["They are identical; both describe packet headers", "They're distinct, and encryption treats them differently."],
        ["Metadata is always encrypted; payload never is", "This also reverses them."]],
      ["An analyst needs to replay the exact bytes of a suspicious session later as ground-truth evidence. Which source is required?",
        ["Full-packet capture", "Only FPC records every byte for exact replay, even if the payload is ciphertext."],
        ["NetFlow", "Flow has no content, so the session can't be replayed."],
        ["Authentication logs", "Logs record events, not raw packets."],
        ["DNS logs", "DNS logs record lookups only."]],
      ["A small company can't afford to store full packet captures but wants network-wide visibility of who talked to whom, including over encrypted sessions. What should it collect?",
        ["Flow records (NetFlow/IPFIX)", "Flow is cheap, scalable, and unaffected by encryption, so it reveals endpoints, volumes, and rhythm without storing payloads."],
        ["Full-packet capture of every link", "That's the most storage-expensive option, which they can't afford."],
        ["Only antivirus alerts", "AV alerts don't show network conversations."],
        ["DHCP lease logs only", "Leases map addresses to hosts but don't show conversations."]]
    ],

    "SPAN, taps & sensor placement": [
      ["What is the main drawback of a SPAN (port mirror) for feeding an IDS?",
        ["It can silently drop frames when the switch is busy", "SPAN is cheap and software-configurable but not perfectly reliable."],
        ["It costs much more than a hardware tap", "SPAN is usually the cheaper option."],
        ["It requires physically cutting the cable", "A SPAN port is configured in software."],
        ["It can only copy encrypted traffic", "It copies whatever traffic flows through the mirrored ports."]],
      ["What is a network tap?",
        ["Passive hardware that reliably copies traffic to a sensor", "Taps are more reliable than SPAN, but cost money and require physical placement."],
        ["A switch feature that mirrors ports in software", "That's SPAN."],
        ["An appliance that decrypts TLS for inspection", "That's an inspection proxy."],
        ["A Wi-Fi access point used for monitoring", "Taps are wired capture devices."]],
      ["A sensor sits only at the internet edge. What will it miss?",
        ["East-west traffic between internal hosts", "Perimeter sensors see inbound scans and brute force but are blind to traffic that never crosses the edge."],
        ["Inbound port scans from the internet", "Edge sensors see inbound scans."],
        ["Inbound brute-force login attempts", "Edge sensors see those too."],
        ["Nothing; the edge sees all traffic", "Internal traffic never crosses the edge."]],
      ["A sensor sits only on an internal segment. What is it blind to?",
        ["Perimeter activity that doesn't reach that segment", "Internal sensors see east-west traffic but not what happens at the edge."],
        ["East-west traffic between internal hosts", "That's exactly what internal sensors see."],
        ["The metadata of encrypted traffic it sees", "Metadata is visible to any sensor on the path."],
        ["Traffic on its own network segment", "It sees its own segment."]],
      ["Why do mature monitoring programs place sensors at multiple choke points?",
        ["Every location has blind spots, so no single sensor sees it all", "The edge and internal segments each have blind spots."],
        ["Multiple sensors make encryption unnecessary", "Sensors observe. They don't replace encryption."],
        ["Regulations require exactly three sensors", "No fixed number is required."],
        ["A single sensor would decrypt too much traffic", "Sensors don't automatically decrypt."]],
      ["Which NIST SP 800-53 control treats sensor placement and system monitoring as a deliberate design decision?",
        ["SI-4, System Monitoring", "SI-4 covers operating sensors, IDS/IPS, and traffic analysis for defensible visibility."],
        ["AU-2, Event Logging", "AU-2 is about what events to log."],
        ["SC-7, Boundary Protection", "SC-7 is about segmentation and boundaries."],
        ["CM-2, Baseline Configuration", "CM-2 is about configuration baselines."]]
    ],

    "Encryption paradox & metadata": [
      ["What is the \"encryption paradox\"?",
        ["Encryption hides attackers' traffic from defenders too", "TLS and SSH guarantee confidentiality for everyone, adversaries included."],
        ["Stronger encryption always makes systems less secure", "That isn't the paradox."],
        ["Encryption can be broken by encrypting twice", "That's false."],
        ["Encrypted data takes up less space than plaintext", "That's false and unrelated."]],
      ["Which of the following remains visible to an observer even when a session uses TLS?",
        ["IPs, ports, timing, and packet sizes", "The cipher protects the cargo, not the label. Routing requires those headers."],
        ["The HTTP request body and headers", "That's encrypted payload."],
        ["The password the user typed", "That's inside the encrypted payload."],
        ["The content of downloaded files", "That's encrypted payload."]],
      ["In most TLS today, which field reveals the hostname the client is requesting, in the clear?",
        ["Server Name Indication (SNI)", "SNI usually travels unencrypted, and the server's certificate is also observable."],
        ["The HTTP Host header", "In HTTPS, the Host header is inside the encrypted payload."],
        ["The TCP checksum", "Checksums don't contain hostnames."],
        ["The DMARC record", "DMARC is email policy in DNS."]],
      ["What is a JA3/JA4 fingerprint?",
        ["A client fingerprint built from TLS handshake parameters", "It works even when nothing inside the session is readable."],
        ["A hash of the decrypted session payload", "It's built from handshake metadata, not decrypted content."],
        ["A biometric login used for user authentication", "It isn't biometric."],
        ["A DNS record type used to locate servers", "It isn't DNS."]],
      ["Which protocol announces itself with a cleartext version banner before encryption fully engages?",
        ["SSH", "SSH exchanges a version banner in the clear, which can reveal tooling such as libssh used by hydra."],
        ["IPsec in tunnel mode", "IPsec doesn't exchange a readable application banner like SSH does."],
        ["AES-GCM", "AES-GCM is a cipher mode, not a protocol with banners."],
        ["DNSSEC", "DNSSEC signs DNS records and has no session banner."]],
      ["Research shows that page identities and even spoken phrases over encrypted channels can sometimes be inferred. From what?",
        ["Packet size and timing patterns", "The length of encrypted records correlates with content, so traffic analysis can infer it without decrypting."],
        ["Weak AES keys", "Strong encryption isn't broken here. The metadata leaks."],
        ["Leaked private keys", "No keys are involved."],
        ["Plaintext in the TCP header", "TCP headers don't contain the content."]],
      ["What is steganography?",
        ["Hiding that a message exists at all", "Steganography doesn't scramble a message. It conceals that there is one."],
        ["Scrambling a message so it can't be read", "That's encryption."],
        ["A one-way fingerprint of data", "That's hashing."],
        ["Signing a message with a private key", "That's a digital signature."]],
      ["An investigator suspects a compromised account but the traffic is encrypted. Per the chapter, what is a good first place to look?",
        ["Sign-in history (location, device, time)", "Encryption hides content, but login metadata survives and often reveals the anomaly."],
        ["The TLS ciphertext, decoded by hand", "Strong ciphertext can't be read."],
        ["The DNS root servers' query logs", "They won't show account activity."],
        ["The Wi-Fi SSID broadcast logs", "These are irrelevant to account compromise."]],
      ["Which of the following does TLS or SSH encryption actually protect?",
        ["The content, such as keystrokes, files, and credentials", "Encryption protects the application payload. Endpoints, timing, and sizes remain exposed."],
        ["The source and destination IP addresses", "IP headers must be readable for routing."],
        ["The timing and rhythm of connections", "Timing is visible metadata."],
        ["The SSH version banner exchange", "SSH's version banner is sent in cleartext."]]
    ],

    "Encrypted-traffic analysis & C2": [
      ["What is encrypted-traffic analysis (ETA)?",
        ["Drawing conclusions from metadata without decrypting", "ETA is powerful but probabilistic. It yields inference, not proof."],
        ["Decrypting all traffic at the perimeter", "That's TLS inspection."],
        ["Brute-forcing TLS session keys offline", "ETA never decrypts anything."],
        ["Scanning file hashes against a malware list", "That's signature antivirus."]],
      ["What is a key limitation of encrypted-traffic analysis?",
        ["It yields inference, not proof of what was done", "To see what was actually done, pivot to host logs."],
        ["It requires breaking the encryption first", "It specifically doesn't break encryption."],
        ["It can't detect periodic beaconing", "Beaconing is one of its strengths."],
        ["It only works on unencrypted traffic", "It's designed for encrypted traffic."]],
      ["An implant on a host contacts the same external server every 60 seconds over HTTPS. What is this pattern, and how can it be spotted despite encryption?",
        ["Beaconing, visible in flow and timing data", "The periodic call-home betrays the malware even when every packet is ciphertext."],
        ["Port scanning, visible in auth.log", "Scanning hits many ports. This is a regular callback."],
        ["DHCP starvation, caught by DHCP snooping", "That's an address pool attack."],
        ["Steganography, found by decrypting images", "This is a timing-based callback pattern."]],
      ["What is command-and-control (C2) traffic?",
        ["The channel between an attacker and their implant on a victim", "Attackers send commands, and the implant returns stolen data and status."],
        ["Traffic between two routers exchanging routes", "That's routing protocol traffic."],
        ["A firewall's management interface traffic", "That's admin traffic."],
        ["A user's normal web browsing session", "C2 deliberately mimics browsing, but it isn't browsing."]],
      ["Why is C2 that runs over HTTPS on port 443 hard to spot?",
        ["It looks just like normal web browsing", "This is the encryption paradox: content is hidden from defenders too."],
        ["Port 443 is never logged by firewalls", "443 traffic can be logged and flowed like anything else."],
        ["HTTPS traffic can never be blocked", "It can be filtered, but blocking all of it is impractical."],
        ["C2 traffic always uses UDP instead", "This C2 uses TLS over TCP 443."]],
      ["Which monitoring approach catches a brute-force by its rhythm even when every packet is encrypted?",
        ["Flow/metadata analysis of connection rhythm", "The rhythm of automation is visible without decryption."],
        ["Reading the SSH session contents on the wire", "SSH content is encrypted."],
        ["Comparing file hashes to antivirus signatures", "This is a network behavior, not a file."],
        ["DNSSEC validation of each connection", "DNSSEC doesn't watch SSH."]]
    ],

    "TLS inspection": [
      ["What motivates an organization to deploy a TLS-inspection proxy?",
        ["Malware hides inside TLS, which can't be inspected encrypted", "The proxy is the encryption paradox turned around: decrypt, inspect, re-encrypt."],
        ["To speed up employees' web browsing", "Inspection adds overhead."],
        ["To provide end-to-end encryption to users", "It breaks end-to-end encryption."],
        ["To replace the need for TLS certificates", "It still relies on certificates."]],
      ["What separates a TLS-inspection proxy from an adversary-in-the-middle attack?",
        ["Only authorization and consent", "Both terminate, decrypt, and re-originate the session."],
        ["The proxy uses stronger encryption", "Cipher strength isn't the distinction."],
        ["The proxy doesn't decrypt the traffic", "It does decrypt traffic."],
        ["The proxy only ever reads metadata", "It reads the payload."]],
      ["A security team's TLS proxy can't inspect a set of employee SSH sessions. Why?",
        ["SSH isn't TLS, so a TLS proxy can't decrypt it", "TLS inspection only applies to TLS traffic."],
        ["SSH traffic is unencrypted, so there's nothing to inspect", "SSH is encrypted."],
        ["SSH runs over UDP, which the proxy ignores", "SSH runs over TCP."],
        ["The proxy needs a bigger certificate key", "Key size isn't the issue."]],
      ["A mobile banking app stops working when employees connect through the corporate TLS-inspection proxy. What is the likely cause?",
        ["The app pins its certificate and rejects the proxy's", "Inspection fails against pinning, because the app only trusts the expected certificate."],
        ["The app doesn't use any encryption at all", "Then the proxy wouldn't interfere."],
        ["The proxy is blocking the app's DNS lookups", "DNS isn't the cause here."],
        ["The app is still using the old TLS 1.0", "The breakage comes from pinning, not the version."]],
      ["What did US-CERT alert TA17-075A warn about HTTPS interception products?",
        ["Many fail to validate the real server's certificate properly", "The browser's protection has to be rebuilt in the proxy, or the cure introduces the disease."],
        ["They make TLS traffic impossible to decrypt", "Decrypting is their whole purpose."],
        ["They always improve TLS security overall", "The alert was titled \"HTTPS Interception Weakens TLS Security.\""],
        ["They only work with SSH, not with TLS", "They work with TLS, not SSH."]],
      ["Which is a cost an organization accepts when deploying TLS inspection?",
        ["It breaks end-to-end encryption and raises privacy concerns", "Every byte passes through an approved interceptor, which has trust and legal implications."],
        ["It makes certificate pinning stronger", "It conflicts with pinning."],
        ["It prevents all malware from getting in", "It improves visibility but doesn't stop everything."],
        ["It removes the need to keep host logs", "Host logs remain essential."]]
    ],

    "Logs & attack signatures": [
      ["An SSH session is fully encrypted, and tshark shows only \"Encrypted packet.\" How can a defender still confirm a brute-force preceded it?",
        ["auth.log shows many failures from one IP, then a success", "Encryption hides content, not behavior. The endpoint logs after decryption."],
        ["Decrypt the session with the server's public key", "Public keys can't decrypt the session."],
        ["Check the DNSSEC signatures on the connection", "DNSSEC is unrelated."],
        ["It's impossible to know once traffic is encrypted", "Both metadata and host logs reveal it."]],
      ["Which brute-force signature is the most actionable, because it marks the moment the defense was breached?",
        ["Many failures followed by a success from the same IP", "Failure-then-success means the attacker got in, which maps to T1078, Valid Accounts."],
        ["A single failed login from one user", "One failure is normal user error."],
        ["A successful login from the usual office IP", "That's expected activity."],
        ["A DNS lookup for the company website", "That's normal traffic."]],
      ["auth.log shows one source trying \"root\", \"admin\", and \"oracle\" in quick succession. What signature is this?",
        ["Username cycling", "Trying many common account names from one source is a classic brute-force or spray indicator."],
        ["Beaconing", "Beaconing is periodic callbacks."],
        ["Steganography", "That's hiding data."],
        ["Cache poisoning", "That's DNS."]],
      ["A web server's access.log shows a burst of 404s, a scanner User-Agent, and requests for /admin, /.git, and /wp-login.php. What is happening, and which ATT&CK technique maps to it?",
        ["Reconnaissance (T1595.001, Active Scanning)", "These are recon signatures: probing paths to map the application."],
        ["Password brute force (T1110, Brute Force)", "Brute force targets logins with many password attempts."],
        ["Log wiping (T1070, Indicator Removal)", "That's deleting logs."],
        ["Traffic capture (T1040, Network Sniffing)", "That's capturing traffic."]],
      ["An attacker who cracked an SSH password through brute force now logs in with it. Which ATT&CK technique describes this login step?",
        ["T1078, Valid Accounts", "Using real credentials is what turns a brute force into a breach."],
        ["T1110, Brute Force", "That's the guessing step before it."],
        ["T1595.001, Active Scanning", "That's recon."],
        ["T1040, Network Sniffing", "That's capturing traffic."]],
      ["The attacker runs tcpdump on a compromised host to capture traffic. Which ATT&CK technique is this?",
        ["T1040, Network Sniffing", "The same technique also describes hostile monitoring of a wire."],
        ["T1078, Valid Accounts", "That's logging in with real credentials."],
        ["T1070, Indicator Removal", "That's wiping logs."],
        ["T1110, Brute Force", "That's guessing passwords."]],
      ["Which log source captured the SSH brute force in the chapter's case?",
        ["The host's auth.log", "auth.log records every login attempt in plaintext, even though the session itself was encrypted."],
        ["The web server's access.log", "access.log captured the web recon, not the SSH logins."],
        ["The DNS resolver's cache", "DNS doesn't record SSH logins."],
        ["The DHCP lease table", "DHCP leases don't record logins."]],
      ["The web access.log shows a recon scan, and auth.log shows an SSH brute force an hour later from the same IP. What lets an analyst confidently stitch these into one campaign timeline?",
        ["Centralized logs with NTP-synced clocks", "Correlation needs the records side by side and timestamps that agree. Otherwise they're disconnected fragments."],
        ["Full-disk encryption on both servers", "FDE protects data at rest and doesn't help correlate events."],
        ["A longer TTL on the company's DNS records", "DNS caching is unrelated to log correlation."],
        ["Deleting older log entries to reduce noise", "Deleting logs destroys evidence."]]
    ],

    "Log integrity & centralization": [
      ["An attacker who lands on a host deletes auth.log to cover their tracks. Which ATT&CK technique is this, and what defeats it?",
        ["T1070; ship logs off-host to a central store", "Local tampering can't reach the authoritative central copy."],
        ["T1110; enforce an account lockout policy", "Lockout doesn't protect logs."],
        ["T1040; encrypt all traffic in transit", "Encryption doesn't stop log deletion."],
        ["T1595.001; deploy a web application firewall", "A WAF doesn't protect host logs."]],
      ["Why is synchronized time (NTP) a prerequisite for using logs as evidence?",
        ["Logs can only be correlated if their clocks agree", "Without synced clocks, web recon and SSH brute force are fragments that can't be stitched together."],
        ["NTP encrypts the logs in transit", "NTP synchronizes clocks. It doesn't encrypt."],
        ["NTP prevents attackers deleting logs", "Centralization addresses deletion."],
        ["NTP compresses logs to save space", "NTP doesn't compress anything."]],
      ["What three benefits does centralized logging deliver?",
        ["Integrity, correlatability, and availability", "A wiped local log can't reach the central copy, sources sit side by side, and there's one place to search."],
        ["Confidentiality, encryption, and compression", "These aren't the stated benefits."],
        ["Speed, anonymity, and deletion", "Deletion is what centralization protects against."],
        ["Authentication, authorization, and accounting", "That's AAA, not logging benefits."]],
      ["Why must log retention outlast the attacker's patience?",
        ["Breaches are often found months after the intrusion", "Retention is driven by investigation needs and compliance."],
        ["Old logs automatically delete malware", "Logs don't remove malware."],
        ["Longer retention improves NTP accuracy", "It's unrelated to time sync."],
        ["Attackers can't read logs older than 30 days", "That's not true."]],
      ["What is a SIEM's role in continuous monitoring?",
        ["It ingests, correlates, and alerts on centralized logs", "The SIEM is the practical engine of continuous monitoring (SP 800-137)."],
        ["It encrypts traffic between company sites", "That's a VPN."],
        ["It assigns IP addresses to new devices", "That's DHCP."],
        ["It sits inline and blocks malicious traffic", "That's an IPS or firewall."]],
      ["What does NIST SP 800-137 (ISCM) reframe monitoring as?",
        ["Ongoing awareness instead of periodic review", "Logs are collected, analyzed, and acted upon as a steady stream."],
        ["An annual audit checklist", "That's the periodic approach ISCM replaces."],
        ["A one-time penetration test", "That's testing, not continuous monitoring."],
        ["A firewall rule standard", "That's SP 800-41."]],
      ["Which NIST publication is the Guide to Computer Security Log Management?",
        ["SP 800-92", "SP 800-92 covers what to log, protecting logs, centralization, and retention."],
        ["SP 800-94", "SP 800-94 covers IDS/IPS."],
        ["SP 800-137", "SP 800-137 covers continuous monitoring."],
        ["SP 800-115", "SP 800-115 covers security testing."]],
      ["Which SP 800-53 controls form the operational backbone of event logging and audit review?",
        ["AU-2 and AU-6", "These cover collecting, alerting on, reviewing, and retaining audit logs."],
        ["SC-7 and CM-7", "These cover boundaries and least functionality."],
        ["SI-4 and SC-7", "SI-4 is monitoring, but SC-7 is boundary protection."],
        ["CM-2 and CM-7", "These are configuration controls."]],
      ["A database server never sent its logs anywhere, and an intrusion went unnoticed for three weeks. Which failure does this illustrate?",
        ["A security logging and alerting failure", "Logs that exist but aren't collected or reviewed don't help detection."],
        ["A broken or expired TLS certificate", "Certificates aren't the issue."],
        ["DNS cache poisoning of the resolver", "DNS isn't the issue."],
        ["VLAN hopping across the trunk", "Segmentation isn't the issue."]]
    ],

    "IDS & IPS": [
      ["What is the key difference between an IDS and an IPS?",
        ["An IDS alerts out of band; an IPS blocks inline", "An IDS watches a copy of traffic from a SPAN or tap. An IPS is in the traffic path."],
        ["An IDS blocks inline; an IPS only alerts", "This reverses them."],
        ["Both sit inline and block traffic", "Only the IPS is inline."],
        ["An IDS encrypts traffic; an IPS decrypts it", "Neither does that."]],
      ["Why would a HIDS catch an SSH brute force that a NIDS on the same segment cannot fully see?",
        ["It runs where decryption happens and can read auth.log", "A NIDS sees only metadata on encrypted traffic. It can flag the rhythm but can't read the session."],
        ["A NIDS can't see any of the traffic at all", "A NIDS sees traffic and metadata, just not encrypted content."],
        ["A HIDS decrypts SSH traffic on the wire", "It reads host data, not wire traffic."],
        ["A NIDS only works on wireless networks", "A NIDS works on wired segments."]],
      ["What can a NIDS do against an encrypted SSH brute force?",
        ["Flag the rhythm, but not read the session", "On encrypted traffic, a NIDS is reduced to metadata."],
        ["Read every password the attacker tried", "Passwords are inside the encrypted session."],
        ["Nothing at all once traffic is encrypted", "It can still see connection rhythm and the SSH banner."],
        ["Decrypt the session using the host key", "Host keys authenticate the server. They don't let a NIDS decrypt sessions."]],
      ["On increasingly encrypted networks, whose vantage point becomes decisive for detection?",
        ["The host-based IDS (HIDS)", "The HIDS lives where decryption happens, so it sees the plaintext events."],
        ["The network-based IDS (NIDS)", "A NIDS is limited to metadata on encrypted traffic."],
        ["The DNS resolver", "DNS sees lookups only."],
        ["The DHCP server", "DHCP sees address assignments only."]],
      ["Which NIST publication is the reference for IDS/IPS architecture, NIDS vs. HIDS, signature vs. anomaly, and tuning?",
        ["SP 800-94", "SP 800-94 is the Guide to Intrusion Detection and Prevention Systems."],
        ["SP 800-92", "SP 800-92 is log management."],
        ["SP 800-41", "SP 800-41 is firewalls."],
        ["SP 800-207", "SP 800-207 is zero trust."]],
      ["An IPS sees the hydra brute force against SSH and drops further connections from that IP. What kind of control is this?",
        ["Preventive", "An IPS sits inline and blocks, which makes it preventive. An IDS that only alerts is detective."],
        ["Detective only", "Blocking makes it preventive."],
        ["Corrective", "Corrective controls restore or fix after an incident, such as patching."],
        ["Deterrent", "Deterrents discourage attempts, like warning banners."]],
      ["An IDS is fed by a SPAN port and suddenly crashes. What happens to production network traffic?",
        ["It keeps flowing, since the IDS only watches a copy", "Being out of band means an IDS failure costs visibility, not connectivity. An inline IPS failure could disrupt traffic."],
        ["All traffic stops until the IDS restarts", "That's a risk with inline devices like an IPS, not an out-of-band IDS."],
        ["Traffic is rerouted through the IDS's backup port", "There's no rerouting, because the IDS was never in the path."],
        ["The switch shuts down the SPAN source ports", "Switches don't disable source ports when a monitor fails."]]
    ],

    "Detection methods & tuning": [
      ["What distinguishes signature-based from anomaly-based detection?",
        ["Signatures match known-bad patterns; anomaly flags deviations", "Signatures are precise but blind to novel attacks. Anomaly detection catches the unknown but produces more false positives."],
        ["Signatures catch unknown attacks; anomaly only catches known ones", "This reverses them."],
        ["Anomaly detection never produces false positives", "It typically produces more."],
        ["Both rely only on comparing file hashes", "Anomaly detection relies on behavior baselines."]],
      ["Which detection approach is precise and low-noise but blind to any attack it has never seen before?",
        ["Signature-based detection", "Matching known-bad patterns like an exploit string or a tool's banner is accurate, but novel attacks have no signature yet."],
        ["Anomaly-based detection", "Anomaly detection can catch the unknown, at the cost of more noise."],
        ["Unsupervised AI-driven NDR", "NDR targets the unknown-unknowns."],
        ["Encrypted-traffic analysis", "ETA infers from metadata. It isn't defined by known-bad patterns."]],
      ["A host that normally makes a few SSH connections suddenly opens hundreds. Which detection method is best suited to flag this?",
        ["Anomaly-based detection", "This is a deviation from the baseline, and there may be no specific signature for it."],
        ["Signature-based antivirus", "There's no file hash to match."],
        ["DNSSEC validation", "That's unrelated."],
        ["Cryptographic erase", "That's sanitization."]],
      ["Why can an untuned anomaly-based IDS be worse than having none?",
        ["Alert fatigue causes real alerts to be ignored", "An alert for everything becomes an alert for nothing."],
        ["It blocks all legitimate network traffic", "An IDS alerts and doesn't block."],
        ["It decrypts employees' private data", "An IDS doesn't decrypt."],
        ["It can't generate any alerts at all", "The problem is too many alerts."]],
      ["Which error is generally considered costlier: a false positive or a false negative?",
        ["A false negative, a real attack missed entirely", "A false positive wastes time. A false negative lets the breach proceed undetected."],
        ["A false positive, a benign event flagged", "It's costly in volume, but a missed attack is worse."],
        ["They are always exactly equally costly", "Their consequences differ greatly."],
        ["Neither type of error has any real cost", "Both have real costs."]],
      ["A team raises IDS sensitivity to catch more attacks. What predictable side effect follows?",
        ["False positives increase", "Cutting false negatives by raising sensitivity makes false positives explode. No setting eliminates both."],
        ["False negatives increase", "Raising sensitivity reduces false negatives."],
        ["Both error types drop to zero", "That's impossible. There's always a trade-off."],
        ["Encryption gets stronger", "IDS settings don't affect encryption."]],
      ["What is IDS tuning?",
        ["Ongoing adjustment of rules and thresholds", "Tuning deliberately trades false positives against false negatives."],
        ["Turning the IDS off during busy hours", "That creates blind spots."],
        ["Encrypting the IDS alerts", "That's unrelated to tuning."],
        ["Buying a second IDS", "Duplication isn't tuning."]],
      ["An IDS detects 99% of attacks and has a 1% false-positive rate, and 1% of events are actual attacks. Given an alert, what is the probability it's a real attack?",
        ["About 50%", "By Bayes: (0.99 × 0.01) / (0.99 × 0.01 + 0.01 × 0.99) = 0.0099 / 0.0198 = 0.50. Low base rates make even accurate detectors noisy."],
        ["About 99%", "That confuses detection rate with the probability that an alert is real, ignoring the base rate."],
        ["About 1%", "That's the base rate, not the post-alert probability."],
        ["About 90%", "The math gives 50%."]],
      ["Pattern matching, learned correlations, and unsupervised AI respectively target which categories of threats?",
        ["Known-knowns, known-unknowns, and unknown-unknowns", "Signatures catch what you've met before, correlations catch new variants of known families, and autonomous AI reaches for net-new malware."],
        ["Unknown-unknowns, known-knowns, and known-unknowns", "This order is wrong."],
        ["Only known-knowns for all three", "Each method targets a different category."],
        ["Insider threats, phishing, and DDoS", "These are attack types, not knowledge categories."]],
      ["What does AI-driven Network Detection and Response (NDR) add over signature-based tools?",
        ["It flags anomalies that no signature exists for yet", "NDR targets novel behavior."],
        ["It eliminates all false positives", "Anomaly approaches still produce false positives."],
        ["It decrypts all TLS traffic automatically", "NDR analyzes behavior and doesn't inherently decrypt."],
        ["It replaces the need for host logs", "Logs remain essential."]],
      ["Testing that detections actually fire and tuning false positives and negatives falls primarily under which CISSP domain?",
        ["Domain 6: Security Assessment & Testing", "Treating detection coverage and log review as testable controls is Domain 6."],
        ["Domain 2: Asset Security", "Domain 2 covers data classification and handling."],
        ["Domain 8: Software Development Security", "Domain 8 covers secure coding."],
        ["Domain 1: Security & Risk Management", "Domain 1 covers governance."]]
    ],

    "Mapping attacks to controls": [
      ["For the hydra SSH brute force (T1110), which control set fits best?",
        ["Failure-rate alerting, rate limiting, and IPS blocking", "These catch and stop repeated failed logins."],
        ["DNSSEC and DHCP snooping on the LAN", "Those defend DNS and DHCP."],
        ["Cryptographic erase of the SSH server", "That's sanitization."],
        ["Hiding the SSH version banner only", "Hiding the banner is obscurity and doesn't stop guessing."]],
      ["For Valid Accounts (T1078), meaning a login with a cracked password, which detection fits best?",
        ["Failure-then-success and impossible-travel alerts", "A valid login looks legitimate on its own. Context and correlation reveal it."],
        ["Signature-based antivirus scans", "There's no malicious file involved."],
        ["Port security on the access switches", "That's unrelated to credential misuse."],
        ["Longer DHCP lease times", "That's unrelated."]],
      ["For an encrypted session whose payload is opaque to the wire, which control approach fits?",
        ["Analyze metadata (SNI, JA3, timing), then pivot to host logs", "Analyze what's visible on the wire, then confirm on the endpoint."],
        ["Brute-force the TLS session keys offline", "That's computationally infeasible."],
        ["Block all encrypted traffic at the edge", "That's impractical and breaks the business."],
        ["Disable logging to save storage space", "Logs are the key evidence."]],
      ["Network monitoring, packet capture, and NIDS limits on encrypted traffic belong primarily to which CISSP domain?",
        ["Domain 4: Communication & Network Security", "Domain 4 is the primary domain for this chapter's network monitoring topics."],
        ["Domain 7: Security Operations", "Domain 7 is secondary here, covering logging operations and the SIEM."],
        ["Domain 3: Security Architecture & Engineering", "Domain 3 covers architecture and crypto design."],
        ["Domain 5: Identity & Access Management", "Domain 5 covers identity."]],
      ["Centralized, synchronized, tamper-resistant logging and SIEM operations fall primarily under which CISSP domain?",
        ["Domain 7: Security Operations", "Running logging and continuous monitoring day to day is security operations."],
        ["Domain 8: Software Development Security", "That covers building software."],
        ["Domain 2: Asset Security", "That covers data classification."],
        ["Domain 4: Communication & Network Security", "Domain 4 is primary for network visibility, but log operations sit in Domain 7."]]
    ]
  }
});
