// Chapter 5 — Vulnerability & Remediation
addChapter({
  id: "ch5",
  number: "5",
  title: "Vulnerability, Malware & Remediation",
  topics: {
    "Vulnerabilities & exploitation": [
      ["What is the difference between a vulnerability and an exploit?",
        ["A vulnerability is the weakness; an exploit is what leverages it", "The weakness exists whether or not anyone uses it. The exploit turns it into impact."],
        ["They are two names for exactly the same thing", "They're distinct concepts."],
        ["An exploit is the weakness; a vulnerability is the attack code", "This reverses the definitions."],
        ["Vulnerabilities are in hardware; exploits are in software", "Both can exist in either."]],
      ["A flaw lets an attacker run their own code on a server over the network with no credentials or physical access. What is this class of vulnerability?",
        ["Remote code execution (RCE)", "RCE is among the most severe classes because it gives an attacker code execution from afar."],
        ["Denial of service", "DoS disrupts availability. It doesn't run attacker code."],
        ["Information leakage", "Leakage reveals data. It doesn't execute code."],
        ["Privilege escalation", "Escalation raises existing access and usually requires a foothold first."]],
      ["An attacker gains initial access by exploiting an unpatched flaw in an internet-facing web app. Which ATT&CK technique is this?",
        ["T1190, Exploit Public-Facing Application", "T1190 covers initial access via exposed apps, VPNs, mail servers, or APIs, e.g., SQLi or unpatched CVEs like Log4Shell or MOVEit."],
        ["T1059, Command and Scripting Interpreter", "T1059 is the execution step that follows."],
        ["T1078, Valid Accounts", "T1078 is logging in with real credentials."],
        ["T1110, Brute Force", "T1110 is password guessing."]],
      ["After exploiting a web server, the attacker spawns cmd.exe from w3wp.exe and runs PowerShell to download payloads. Which technique describes this?",
        ["T1059, Command and Scripting Interpreter", "Using built-in shells (PowerShell .001, cmd .003, bash .004) is \"living off the land\" execution."],
        ["T1190, Exploit Public-Facing Application", "That's the initial access step before this."],
        ["T1505.003, Web Shell", "A web shell is a persistent backdoor script, a specific persistence technique."],
        ["T1070, Indicator Removal", "That's wiping evidence."]],
      ["Why is \"living off the land\" hard to detect?",
        ["It uses built-in tools, so there's no new binary to flag", "Signature tools look for known-bad files. Built-in interpreters look legitimate."],
        ["It only happens on air-gapped networks", "It happens anywhere."],
        ["It encrypts the hard drive before acting", "That's ransomware."],
        ["It relies exclusively on zero-day exploits", "It relies on legitimate tools, not necessarily zero-days."]],
      ["A web server process (w3wp.exe or java) unexpectedly spawns cmd.exe or /bin/sh. What should a defender suspect?",
        ["The web app was exploited and is running commands", "A web server spawning a shell is the classic sign of the exploit → code execution → shell chain."],
        ["A routine Windows update is installing", "Updates don't run through the web server process."],
        ["A user is browsing the site normally", "Browsing doesn't spawn server-side shells."],
        ["DNS cache poisoning of the web server", "That's a resolver attack."]]
    ],

    "CVE, CWE, CVSS & NVD": [
      ["A scanner reports CVE-2021-41773 with a CVSS base score of 9.8. Which value tells you how severe it is, and which system maintains the underlying weakness category?",
        ["CVSS gives severity; CWE gives the category", "CVE is only the identifier, and NVD indexes all of them together."],
        ["CVE gives the severity; CVSS gives the category", "CVE names the flaw. It doesn't score it."],
        ["NVD gives the severity; CVE gives the category", "NVD indexes data. CVE is an identifier, not a category."],
        ["CWE gives the severity; CVE gives the category", "This reverses CWE's and CVSS's roles."]],
      ["Which phrase correctly pairs each system with its verb?",
        ["CVE names, CWE classifies, CVSS scores, NVD indexes", "Mixing up CVE and CWE is the most common trap on this topic."],
        ["CVE scores, CWE names, CVSS classifies, NVD indexes", "These are scrambled."],
        ["CVSS names, CVE classifies, CWE scores, NVD indexes", "These are scrambled."],
        ["NVD names, CVSS indexes, CWE scores, CVE classifies", "These are scrambled."]],
      ["The Apache 2.4.49 bug CVE-2021-41773 is an instance of path traversal. What is path traversal in this framework?",
        ["A CWE weakness category", "CWE answers \"what class of defect,\" which helps prevention across many products."],
        ["A CVE identifier", "The CVE is the specific flaw. Path traversal is its category."],
        ["A CVSS base metric", "CVSS metrics are things like attack vector and complexity."],
        ["An NVD severity level", "NVD reports CVSS scores. It doesn't define categories."]],
      ["Who governs CVSS, and what range does it use?",
        ["FIRST, scoring from 0.0 to 10.0", "CVSS uses base metrics like attack vector, complexity, privileges required, and CIA impacts."],
        ["MITRE, scoring from 1 to 5", "MITRE maintains CWE and ATT&CK."],
        ["NIST, scoring A through F", "NIST runs NVD, and CVSS isn't letter-graded."],
        ["OWASP, scoring 1 to 10 by popularity", "OWASP publishes the Top 10, not CVSS."]],
      ["Which organization runs the National Vulnerability Database (NVD), and what does it do?",
        ["NIST; it enriches CVEs with scores and product data", "NVD is the canonical lookup that scanners and analysts consult."],
        ["MITRE; it assigns CWE categories only", "MITRE maintains CWE. NIST runs NVD."],
        ["FIRST; it writes proof-of-concept exploit code", "FIRST governs CVSS and doesn't write exploits."],
        ["OWASP; it ranks the top web application risks", "That's the OWASP Top 10."]],
      ["Which of these is a CVSS base metric?",
        ["Attack vector", "Base metrics include attack vector, attack complexity, privileges required, and confidentiality/integrity/availability impact."],
        ["The CVE year", "The year is part of the identifier, not the score."],
        ["The vendor's market share", "Market share isn't a CVSS input."],
        ["The CWE number", "The category isn't a scoring metric."]],
      ["An analyst wants to know whether many products share the same root programming mistake so developers can prevent it. Which system helps most?",
        ["CWE", "CWE classifies weakness types, which enables prevention and trend analysis across products."],
        ["CVE", "CVE identifies single flaws, not patterns."],
        ["CVSS", "CVSS scores severity."],
        ["The patch gap", "That's a time interval, not a classification system."]]
    ],

    "Vulnerability lifecycle": [
      ["What is the patch gap?",
        ["The time between disclosure and a host applying the fix", "Attackers target this window. ShopQuest was breached purely in the patch gap."],
        ["The time it takes a vendor to write a patch", "That's development time, before disclosure."],
        ["The difference between two CVSS scores", "That's unrelated."],
        ["A missing rule in the perimeter firewall", "That's unrelated."]],
      ["What makes a zero-day different?",
        ["It's exploited before any fix exists", "There's nothing to patch yet, so detection and other layers must carry the load."],
        ["It's fixed on the same day it's disclosed", "That's the opposite."],
        ["It has a CVSS base score of zero", "Zero-days can be extremely severe."],
        ["It only affects fresh, day-zero installs", "The name refers to defenders having zero days of warning."]],
      ["What is coordinated disclosure?",
        ["Private vendor report, then disclosure with the patch", "This minimizes the window in which attackers know about a flaw but no fix exists."],
        ["Publishing exploit code immediately on social media", "That's full, uncoordinated disclosure."],
        ["Selling the vulnerability to the highest bidder", "That isn't disclosure."],
        ["Keeping the flaw secret from everyone forever", "Secrecy leaves users exposed."]],
      ["Which order represents a vulnerability's life cycle?",
        ["Introduction → discovery → disclosure → weaponization → patching", "Understanding the timeline lets defenders act before attackers do."],
        ["Patching → discovery → introduction → disclosure → weaponization", "Patching comes last."],
        ["Weaponization → introduction → patching → discovery → disclosure", "A flaw must be introduced before anything else happens."],
        ["Disclosure → introduction → patching → weaponization → discovery", "It must exist before it's disclosed."]],
      ["Why is patching, rather than better detection, the expected control for a known-CVE breach?",
        ["A fix existed; patching removes the opportunity entirely", "Vulnerability management eliminates the weakness. Monitoring catches its abuse."],
        ["Detection is impossible for known CVEs", "Known CVEs can be detected. Patching is simply more decisive."],
        ["Patching also removes any existing backdoors", "Patching alone does not remove backdoors already planted."],
        ["CVSS scores require patching within 24 hours", "CVSS doesn't set deadlines."]]
    ],

    "Vulnerability management & scanning": [
      ["What is vulnerability management?",
        ["A continuous cycle of finding and fixing weaknesses", "It's an ongoing program, not a one-time scan."],
        ["A one-time penetration test of key systems", "A pentest is a point-in-time assessment."],
        ["Installing antivirus software on all hosts", "AV is one control, not the management process."],
        ["Writing working exploits for known flaws", "That's offensive work."]],
      ["An unpatched Apache server was breached because no one knew it existed. What foundation of vulnerability management failed?",
        ["Asset inventory", "Inventory turns \"somewhere out there\" into \"host 10.0.0.14, owner X, due for patching.\" Every later step depends on it."],
        ["CVSS scoring", "You can't score what you don't know exists."],
        ["Penetration testing", "Testing can't cover hosts nobody knows about."],
        ["Log retention", "Logs don't reveal untracked assets by themselves."]],
      ["How does an authenticated (credentialed) scan compare with an unauthenticated scan?",
        ["It logs in and reads installed software directly", "The tradeoff is that it requires managed credentials and more trust."],
        ["It sees only what an outside attacker sees", "That's the unauthenticated scan."],
        ["It's faster, but shallower in what it finds", "That also describes unauthenticated scanning."],
        ["It doesn't require any credentials to run", "Credentialed scanning requires credentials by definition."]],
      ["An unauthenticated network scan reports an Apache version from a banner. What is its key limitation?",
        ["It can't see installed packages or config", "It sees ports and banners, which is what an attacker sees, but not what's actually installed or backported."],
        ["It always crashes the target service", "Scans don't normally crash targets."],
        ["It can read the server's private keys", "Scans don't access private keys."],
        ["It requires domain admin rights to run", "Unauthenticated scans use no credentials."]],
      ["What is Zenmap?",
        ["A graphical front end for Nmap", "It runs Nmap scans without the command line and visualizes the results."],
        ["A GPU-based password cracker", "That's Hashcat."],
        ["A SIEM for log correlation", "A SIEM correlates logs."],
        ["A TLS-inspection proxy", "Zenmap doesn't inspect TLS."]],
      ["Which NIST publication covers enterprise patch management: inventory, prioritize, test, deploy, verify?",
        ["SP 800-40", "SP 800-40 frames patching as a disciplined program with risk-based service levels."],
        ["SP 800-115", "SP 800-115 covers security testing."],
        ["SP 800-88", "SP 800-88 covers media sanitization."],
        ["SP 800-63B", "SP 800-63B covers authentication."]],
      ["A mature patch program tests patches before deployment and schedules them within risk-based targets. Why test first?",
        ["To avoid breaking production while still patching on schedule", "Untested patches can cause outages. Risk-based SLAs keep testing from becoming indefinite delay."],
        ["Because most vendor patches are malicious", "Patches aren't usually malicious, though integrity verification matters."],
        ["To give attackers time to exploit first", "Testing should be quick, not a deliberate delay."],
        ["Testing replaces the need to verify installation", "Installation still has to be confirmed."]],
      ["A small business wants easy wins for patching. Which set fits the chapter's examples?",
        ["Auto-updates, API key rotation, and dependency alerts", "These are low-effort steps that close common gaps."],
        ["Disable all updates to avoid any downtime", "That widens the patch gap."],
        ["Hide server version banners and nothing else", "That's obscurity. The flaw remains."],
        ["Wait for a breach before patching anything", "That's reactive and costly."]]
    ],

    "Security testing & pentests": [
      ["How does a penetration test differ from a vulnerability assessment?",
        ["A pentest exploits findings; an assessment only reports them", "NIST SP 800-115 is the technical guide for both."],
        ["An assessment exploits findings; a pentest only reports them", "This reverses them."],
        ["They are identical activities with different names", "They differ in depth and intent."],
        ["A pentest, unlike an assessment, needs no authorization", "Every pentest requires explicit written authorization."]],
      ["A tester is given no internal knowledge and works from outside to simulate an external attacker. What type of test is this?",
        ["Black box", "Black box means no prior knowledge, simulating an outsider."],
        ["White box", "White box gives full knowledge, including source code."],
        ["Grey box", "Grey box gives partial knowledge, like a low-privilege account."],
        ["Purple box", "That isn't a standard testing type."]],
      ["Testers receive a low-privilege account and basic architecture diagrams to simulate an insider. What type of test is this?",
        ["Grey box", "Partial knowledge simulates an insider or an attacker with a foothold."],
        ["Black box", "Black box testers have no knowledge."],
        ["White box", "White box testers get full knowledge, including source and config."],
        ["Red box", "That isn't a standard type."]],
      ["Which test type maximizes coverage and efficiency by giving testers source code and configuration?",
        ["White box", "Full knowledge lets testers find flaws that are invisible from outside."],
        ["Black box", "Black box gives the least knowledge and the least coverage per hour."],
        ["Grey box", "Grey box gives only partial knowledge."],
        ["Unauthenticated scanning", "That's a scan type, not a pentest knowledge level."]],
      ["During an authorized black-box pentest, you find logs proving a real prior intruder already exfiltrated payment data. What do you do?",
        ["Stop and notify your designated point of contact", "This is now an active incident, not a simulation."],
        ["Continue the test and include it in the final report", "Real incidents need immediate escalation, not a report weeks later."],
        ["Delete the intruder's logs to clean up the system", "That destroys evidence."],
        ["Investigate the intruder's own systems yourself", "That's out of scope and potentially illegal."]],
      ["What do the rules of engagement (RoE) for a pentest document?",
        ["Scope, timing, techniques, exclusions, contacts, and permission", "The RoE is what separates an authorized assessment from a crime."],
        ["Only the format of the final report", "It covers far more than the report."],
        ["The real attacker's likely motivations", "RoE is about the tester's authorized activity."],
        ["The CVSS scores that testers must assign", "Scoring isn't the RoE's purpose."]],
      ["Who must authorize a penetration test?",
        ["Senior/executive management", "Testing without written authorization from someone with the authority to grant it is unethical and illegal."],
        ["The IT team being tested", "They usually lack the authority, and they may also be a conflict of interest."],
        ["The tester themselves", "Testers can't authorize their own work."],
        ["Any employee with admin rights", "Admin rights aren't the authority to approve a test."]],
      ["Which team emulates adversaries, often stealthily and over long campaigns, to test defenses realistically?",
        ["Red team", "Red teams emulate attackers."],
        ["Blue team", "Blue teams defend, detect, and respond."],
        ["Purple team", "Purple is collaboration between red and blue."],
        ["White team", "White teams typically referee exercises. They aren't the attackers."]],
      ["Red shares its techniques with blue as the exercise runs so blue can tune detections. What is this collaboration called?",
        ["Purple teaming", "Purple teaming improves defenses rather than just scoring points."],
        ["Red teaming", "Red alone emulates adversaries."],
        ["Blue teaming", "Blue alone defends."],
        ["Black-box testing", "That's a knowledge level for testers."]],
      ["Which NIST publication is the technical guide to security testing, covering scanning, vulnerability assessment, and pen testing?",
        ["SP 800-115", "SP 800-115 is the technical guide to information security testing."],
        ["SP 800-40", "SP 800-40 is patch management."],
        ["SP 800-92", "SP 800-92 is log management."],
        ["SP 800-41", "SP 800-41 is firewalls."]],
      ["Testing devices for unchanged factory passwords corresponds to which OWASP WSTG test?",
        ["WSTG-ATHN-02", "Default credentials are easily found in manuals, on stickers, or in lists like SecLists and CIRT.net."],
        ["ASVS Level 3", "ASVS is a requirements standard, not this specific test."],
        ["CWE-22", "CWE-22 is path traversal."],
        ["ATT&CK T1190", "That's an ATT&CK technique."]]
    ],

    "OWASP Top 10 & secure coding": [
      ["Database credentials sit in cleartext in config.php. What failure is this, and what is the correct remediation?",
        ["Hard-coded credentials; use a secrets manager and rotate", "Secrets must be injected at runtime, and the exposed one must be rotated since it's already compromised."],
        ["Broken access control; rename the file", "Renaming is obscurity, and the secret is still exposed."],
        ["Injection; add input validation", "No input is involved."],
        ["Insecure design; rewrite the app in another language", "That's an excessive and misdirected fix."]],
      ["Which OWASP category covers untrusted input being interpreted as a command or query, such as SQLi, OS command injection, and XSS?",
        ["Injection", "The fix generalizes: never mix data and code, and use parameterized queries."],
        ["Security misconfiguration", "That's about insecure defaults and settings."],
        ["Broken access control", "That's about doing things you shouldn't be permitted to do."],
        ["Cryptographic failures", "That's about unprotected sensitive data."]],
      ["What is the primary fix for SQL injection?",
        ["Parameterized queries", "When input is never interpreted as part of the query, it can't change the query's logic."],
        ["Hiding error messages only", "That reduces leakage but leaves the injection open."],
        ["Serving the site over HTTPS", "TLS protects transit, not query construction."],
        ["Longer database passwords", "Passwords don't stop injection through the app."]],
      ["A victim's browser runs a script an attacker planted in a forum post. What is this?",
        ["Cross-site scripting (XSS)", "Untrusted content is rendered as executable script in other users' browsers."],
        ["SQL injection", "SQLi targets the database."],
        ["Insecure direct object reference", "IDOR is a missing authorization check on object references."],
        ["Buffer overflow", "That's memory corruption."]],
      ["The SolarWinds incident showed one trusted update compromising thousands of networks. Which OWASP category is this?",
        ["Software supply-chain failures", "You inherit the security of every dependency and update you trust."],
        ["Injection", "No input injection was the root cause."],
        ["Authentication failures", "The issue was a compromised trusted build or update, not weak logins."],
        ["Mishandling of exceptional conditions", "That's about failing open or leaking errors."]],
      ["Which control addresses software and data integrity failures, such as trusting updates you can't verify?",
        ["Code signing", "Signatures prove the bytes you run are exactly what the vendor shipped."],
        ["Hiding the update server's IP", "That's obscurity."],
        ["Disabling logging", "That makes things worse."],
        ["Increasing the CVSS score", "Scores don't verify integrity."]],
      ["An upload form was never designed to reject executable content, and no patch can fix it. Which category is this?",
        ["Insecure design", "Some flaws are built into the design itself and need redesign, not a patch."],
        ["Vulnerable and outdated components", "That's about unpatched dependencies."],
        ["Cryptographic failures", "That's about unprotected sensitive data."],
        ["Security logging and alerting failures", "That's about monitoring gaps."]],
      ["Attackers log in through credential stuffing and password spraying against reused, weak passwords. Which OWASP category is this?",
        ["Authentication failures", "Weak or reused passwords, with no MFA, enable these attacks."],
        ["Injection", "No input is interpreted as code."],
        ["Insecure design", "This is a credential weakness, not a design flaw."],
        ["Server-side request forgery", "That isn't the scenario described."]],
      ["An application crashes and shows a stack trace with file paths and SQL queries. Which category is this, and what's the principle?",
        ["Mishandled exceptions; fail closed and reveal nothing", "Information leakage gives attackers a map of the system."],
        ["Broken access control; add an ACL rule", "This is about error handling."],
        ["Injection; use parameterized queries", "Nothing in the scenario is injection."],
        ["Supply-chain failure; sign all the code", "This is about error handling."]],
      ["Which OWASP category is described as the root cause when a flaw in any dependency becomes a flaw in your application?",
        ["Vulnerable and outdated components", "Modern stacks pull in vast dependency trees, so dependencies must be tracked and patched."],
        ["Insecure design", "That's a design flaw, not inherited components."],
        ["Broken access control", "That's about permissions."],
        ["Security misconfiguration", "That's about settings and defaults."]],
      ["A server ships with sample apps, debug mode on, and unnecessary services enabled. Which category is this?",
        ["Security misconfiguration", "Insecure defaults and unnecessary features expand the attack surface."],
        ["Injection", "No untrusted input is executed here."],
        ["Cryptographic failures", "There's no sensitive data exposure described."],
        ["Authentication failures", "Login weaknesses aren't described."]],
      ["Mirai hijacked IoT devices that still used factory passwords. What should have been done?",
        ["Change default credentials before deployment", "Default credentials need no skill to abuse. Attackers just log in (ATT&CK T1078.001)."],
        ["Hide the devices' Wi-Fi SSIDs", "That's obscurity, and IoT devices are found via Shodan anyway."],
        ["Raise the devices' CVSS score", "Scores don't change device security."],
        ["Hash device firmware names with SHA-256", "That's irrelevant."]]
    ],

    "Input handling, IDOR & memory": [
      ["A user views their invoice at /invoice?id=4471. Changing it to 4472 shows another customer's invoice. What is the flaw and its root cause?",
        ["IDOR: no check that the user may see that object", "An insecure direct object reference is a missing access-control check."],
        ["SQL injection: the ID is executed as code", "The ID works as intended. Authorization is what's missing."],
        ["XSS: a script runs in the user's browser", "No script is involved."],
        ["Buffer overflow: the ID value is too long", "The ID is a normal length."]],
      ["Users can view other customers' invoices by changing the ID in /invoice?id=4471. A developer proposes making the IDs long random strings. Why isn't this a real fix?",
        ["It's obscurity: it delays guessing but isn't authorization", "The fix is a server-side authorization check on every object request."],
        ["Random strings are too slow to generate", "Speed isn't the issue."],
        ["Random IDs would break the site's HTTPS", "It has nothing to do with TLS."],
        ["Random IDs are always guessable in seconds", "They can be hard to guess. That's still not authorization."]],
      ["What is the difference between input validation and input sanitization?",
        ["Validation rejects bad input; sanitization neutralizes it", "Validation rejects bad input. Sanitization makes risky characters harmless."],
        ["They are two names for exactly the same process", "They're complementary but distinct."],
        ["Validation encrypts input; sanitization hashes it", "Neither one encrypts or hashes."],
        ["Sanitization happens only when writing to logs", "Sanitization applies wherever input could be interpreted."]],
      ["A program copies user input into a fixed 64-byte buffer without checking length, and a long input overwrites adjacent memory, including control flow. What is this?",
        ["Buffer overflow", "Skipping the length check lets spillover corrupt memory, potentially hijacking execution."],
        ["SQL injection", "That's query manipulation."],
        ["IDOR", "That's missing authorization on object references."],
        ["Race condition", "That's a timing issue."]],
      ["What does the \"rule of least power\" recommend?",
        ["Use the least powerful mechanism that does the job", "It extends least privilege from accounts to the capabilities of your code itself."],
        ["Give every account admin rights for simplicity", "That's the opposite."],
        ["Use the most powerful language available", "That's the opposite."],
        ["Turn off power to unused servers", "That's a literal misreading."]],
      ["Why is prompt injection considered a form of injection?",
        ["The model treats untrusted input as instructions", "It's the AI equivalent of mixing data and code."],
        ["It always uses SQL syntax in the prompt", "It uses natural language."],
        ["It exploits buffer overflows in the model", "It manipulates instructions, not memory."],
        ["It requires physical access to the server", "It's sent through ordinary input."]],
      ["What is a risk of AI-assisted coding highlighted in the chapter?",
        ["Confident but insecure generated code", "Generated code needs the same (or more) automated security testing."],
        ["AI-generated code usually fails to compile", "It often compiles fine. Security is the concern."],
        ["AI code is always more secure than human code", "Not necessarily."],
        ["AI tools encrypt all of the source code", "They don't."]]
    ],

    "Secure SDLC": [
      ["What is the principle of \"shift left\"?",
        ["Do security work earlier, where fixes are cheaper", "A flaw caught in design costs a fraction of one caught in production, or by an attacker."],
        ["Delay security testing until after release", "That's the opposite."],
        ["Move servers to the left of the network diagram", "That's a literal misreading."],
        ["Assign security only to the operations team", "Shift left involves developers early."]],
      ["What does a secure software development lifecycle (SDLC) do?",
        ["Builds security into every phase of development", "Security isn't treated as a final gate."],
        ["Adds a single security scan right before release", "That's a final gate, which an SDLC avoids."],
        ["Lets developers skip testing to ship faster", "Testing is integral."],
        ["Only applies to open-source software projects", "It applies to all software."]],
      ["Which OWASP resource provides a tiered, testable catalog of security requirements used as both a design checklist and a verification benchmark?",
        ["ASVS", "ASVS levels range from basic to high-assurance."],
        ["OWASP Top 10", "The Top 10 ranks risks. It isn't a requirements catalog."],
        ["OWASP WSTG", "WSTG is a testing guide."],
        ["CVSS", "CVSS scores severity."]],
      ["How does open-source software compare to an open cipher?",
        ["Anyone can find its flaws, defenders and attackers alike", "Openness cuts both ways, though it generally favors the defenders who look."],
        ["Open source is always free of vulnerabilities", "It isn't."],
        ["Open source hides its logic from the public", "That's closed source."],
        ["Open source code can't be audited", "It's the most auditable."]],
      ["Pair each standard with its verb. Which pairing is correct?",
        ["800-40 patches, 800-115 tests, Top 10 prioritizes, ASVS verifies", "Matching standards to verbs is a reliable memory aid."],
        ["800-40 tests, 800-115 patches, Top 10 verifies, ASVS prioritizes", "These are swapped."],
        ["800-40 verifies, 800-115 prioritizes, Top 10 patches, ASVS tests", "These are swapped."],
        ["800-40 prioritizes, 800-115 verifies, Top 10 tests, ASVS patches", "These are swapped."]],
      ["Writing secure code, threat modeling, and OWASP Top 10 work fall under which CISSP domain?",
        ["Domain 8: Software Development Security", "Building maps to Domain 8, testing to Domain 6, configuring to Domain 3, and operating to Domain 7."],
        ["Domain 6: Security Assessment & Testing", "Domain 6 is testing."],
        ["Domain 7: Security Operations", "Domain 7 is operating and responding."],
        ["Domain 4: Communication & Network Security", "Domain 4 is networking."]],
      ["Vulnerability assessments, pentests, and rules of engagement fall under which CISSP domain?",
        ["Domain 6: Security Assessment & Testing", "Testing activities map to Domain 6."],
        ["Domain 8: Software Development Security", "Domain 8 is building software."],
        ["Domain 3: Security Architecture & Engineering", "Domain 3 is configuring and architecture."],
        ["Domain 2: Asset Security", "Domain 2 is data classification."]],
      ["Ongoing patch management and incident response containment fall under which CISSP domain?",
        ["Domain 7: Security Operations", "Operating and responding map to Domain 7."],
        ["Domain 8: Software Development Security", "Domain 8 is building software."],
        ["Domain 6: Security Assessment & Testing", "Domain 6 is testing."],
        ["Domain 1: Security & Risk Management", "Domain 1 is governance."]]
    ],

    "Malware types": [
      ["Malware spreads across the network with no user action, encrypts files including network-attached backups, and demands cryptocurrency. Which two characteristics are combined?",
        ["Ransomware with worm propagation", "The worm reaches network storage and encrypts the backups, removing the easy restore, which is what makes the ransomware effective."],
        ["A virus combined with spyware", "A virus needs user action, and spyware observes rather than encrypts."],
        ["A trojan combined with a logic bomb", "Neither self-propagates."],
        ["A rootkit combined with adware", "Neither matches the propagation and encryption described."]],
      ["What is the key difference between a virus and a worm?",
        ["A virus needs a host and user action; a worm spreads itself", "A worm's independence is what makes it so explosive."],
        ["A worm needs user action; a virus spreads itself", "This reverses them."],
        ["Viruses only affect Macs; worms only affect Windows", "Both affect any platform."],
        ["They are identical, just different names", "They differ in how they spread."]],
      ["A user installs a \"free cracked video editor\" that secretly gives an attacker access. What malware type relied on deception to get installed?",
        ["Trojan horse", "Trojans masquerade as something desirable so the user invites them in. They don't self-replicate."],
        ["Worm", "Worms spread on their own."],
        ["Virus", "Viruses attach to host files and spread when run."],
        ["Logic bomb", "Logic bombs wait for a trigger."]],
      ["Which malware gives an attacker interactive, hands-on remote control of a compromised machine?",
        ["Remote access trojan (RAT)", "A RAT is effectively a hidden backdoor for hands-on operation."],
        ["Spyware that logs keystrokes", "Spyware passively observes."],
        ["A dormant logic bomb", "Logic bombs wait for a trigger."],
        ["Adware that injects ads", "Adware shows ads."]],
      ["Malware gains root-level access and hides its own files and processes, often at or below the kernel, to survive cleanup. What is it?",
        ["Rootkit", "Rootkits conceal privilege and persist invisibly, usually installed after initial entry."],
        ["Worm", "Worms are defined by self-propagation."],
        ["Trojan", "Trojans are defined by deception at install."],
        ["Bot", "Bots are defined by obeying C2."]],
      ["Code planted by a disgruntled admin deletes the payroll database if the admin's account is ever disabled. What is this?",
        ["Logic bomb", "It lies dormant until a trigger condition is met. That's why code review of trusted insiders matters."],
        ["Worm", "It doesn't self-propagate."],
        ["Ransomware", "It doesn't encrypt for payment."],
        ["Spyware", "It doesn't observe and exfiltrate."]],
      ["What is a bot, and what is a botnet used for?",
        ["A compromised machine obeying C2; botnets run DDoS and spam", "Botnets monetize compromised machines at scale."],
        ["A helpful chatbot; used for customer service", "This chapter's term means a compromised machine."],
        ["A type of firewall; used to filter traffic", "Bots are compromised machines."],
        ["A logic bomb; used to delete data", "Different concept."]],
      ["Why are insecure IoT devices prime recruits for DDoS botnets like Mirai?",
        ["They're numerous, exposed, and often keep default passwords", "Mirai's attack on Dyn knocked major sites offline. Shodan makes exposed devices easy to find."],
        ["They have the fastest CPUs of any device", "Their value is their numbers and weak security, not their power."],
        ["They always run unpatched Windows", "Many run embedded Linux."],
        ["They're never connected to the internet", "They're connected, which is the problem."]],
      ["Ransomware operators exfiltrate a copy of data before encrypting it. What is this tactic, and why does it matter?",
        ["Double extortion; paying doesn't undo the theft", "Backups don't help against the leak threat."],
        ["Polymorphism; it changes the malware's hash", "That's about evading signatures."],
        ["Coordinated disclosure; it helps the vendor patch", "That's unrelated."],
        ["Cryptographic erase; it destroys the key", "That's sanitization."]],
      ["DarkSide (Colonial Pipeline) and REvil licensed their malware and infrastructure to affiliates. What is this model?",
        ["Ransomware-as-a-service (RaaS)", "Subscription or profit-share models dramatically lower the skill bar."],
        ["Infrastructure as Code (IaC)", "That's a DevOps practice."],
        ["A bug bounty program", "That's legitimate vulnerability research."],
        ["Purple teaming", "That's a defensive exercise."]],
      ["Which malware quietly logs keystrokes, harvests credentials, and tracks browsing, then sends the data out?",
        ["Spyware", "Spyware observes and exfiltrates."],
        ["Ransomware", "Ransomware encrypts and extorts."],
        ["Worm", "Worms self-propagate."],
        ["Logic bomb", "Logic bombs wait for a trigger."]],
      ["What are the three parts of any malware?",
        ["Infection vector, trigger, and payload", "These are how it arrives, what activates it, and what it does."],
        ["Hash, salt, and pepper", "These are password storage terms."],
        ["Confidentiality, integrity, and availability", "That's the CIA triad."],
        ["Scope, timing, and exclusions", "These are rules of engagement elements."]],
      ["Which description of a DDoS defense is correct?",
        ["Mitigate upstream at the provider, before the link saturates", "SYN floods and amplification (spoofed queries to open DNS or NTP servers) overwhelm the victim's link before local controls can help."],
        ["A stronger local firewall alone stops any DDoS", "A saturated link can't be fixed locally."],
        ["Changing the server's password stops a DDoS", "DDoS isn't about credentials."],
        ["Encrypting all traffic prevents a DDoS", "Encryption doesn't stop floods."]],
      ["In a DNS amplification attack, what does the attacker spoof?",
        ["The victim's IP address", "Small spoofed requests turn into big responses aimed at the target."],
        ["The DNS server's private key", "Amplification doesn't involve keys."],
        ["The victim's MAC address on the LAN", "Amplification works at the IP level across the internet."],
        ["The domain's DMARC record", "That's email policy."]],
      ["Which matching of malware to its defining trait is correct?",
        ["Rootkit: hides privilege", "In short: a virus needs a host, a worm self-propagates, a trojan deceives, a RAT grants access, a rootkit hides privilege, a bot obeys C2, ransomware extorts, a logic bomb waits, and spyware observes."],
        ["Worm: needs a host file", "That's a virus."],
        ["Trojan: self-propagates", "That's a worm."],
        ["Spyware: waits for a trigger", "That's a logic bomb."]]
    ],

    "Malware delivery & evasion": [
      ["Attackers compromise an industry forum their targets are known to visit, rather than attacking the targets directly. What is this?",
        ["Watering-hole attack", "The value is the visitors, not the site itself."],
        ["Typo-squatting", "That's registering look-alike domains."],
        ["Drive-by download from a random ad", "A drive-by can be the delivery mechanism, but a target-chosen site is a watering hole."],
        ["Phishing email", "This attack doesn't use email."]],
      ["An attacker registers \"amazom.com\" to catch users who mistype the real domain. What is this?",
        ["Typo-squatting", "Near-miss domains catch typos to serve phishing or malware."],
        ["A watering-hole attack", "That compromises a real site victims visit."],
        ["DNS cache poisoning", "That forges resolver records."],
        ["An evil-twin attack", "That's a Wi-Fi impersonation."]],
      ["You find a suspicious look-alike domain. A WHOIS lookup shows it's registered to a brand-protection firm. What does this suggest?",
        ["The real company likely bought it defensively", "WHOIS shows registration details, and brand-protection firms often register typo domains to keep them from attackers."],
        ["It's definitely a malicious phishing site", "The registrant suggests a defensive purchase."],
        ["WHOIS proves the site is malware-free", "WHOIS only shows registration, not safety."],
        ["The domain registration has expired", "WHOIS shows it's registered."]],
      ["Which malware hides its code as ciphertext, exposing only a small decryption routine?",
        ["Encrypted virus", "Only the decryptor stub is visible, which frustrates signature matching."],
        ["Logic bomb", "Logic bombs are defined by a trigger, not encryption."],
        ["Kernel-mode rootkit", "Rootkits hide privilege and presence."],
        ["Network worm", "Worms are defined by propagation."]],
      ["Why is signature-based antivirus described as \"fast but brittle\"?",
        ["Exact hash matching is defeated by changing one byte", "Polymorphic malware exploits this by mutating every copy."],
        ["It's slow and can't scan large files", "It's fast."],
        ["It must decrypt all network traffic first", "File-based AV doesn't do that."],
        ["It only works on Linux systems", "It's on all platforms."]],
      ["Which malware distribution channels are named in the chapter?",
        ["Drive-bys, email, removable media, and worms", "Each channel calls for different controls."],
        ["Only email attachments and links", "There are several channels."],
        ["Only infected USB drives", "There are several channels."],
        ["Only malicious DNS records", "DNS isn't a primary channel listed."]],
      ["A \"flat business\" where everyone has broad access is described as risky. Why?",
        ["No layers catch mistakes, so one click can breach everything", "That makes user behavior as critical as any tool. A security champion helps."],
        ["Flat organizations can't afford firewalls", "Cost isn't the point."],
        ["Flat businesses never use any passwords", "That isn't what the term means."],
        ["Flat businesses are immune to phishing", "They're especially exposed."]],
      ["What does a \"security champion\" do in a small organization?",
        ["Shares scams, runs phishing tests, and answers questions", "A champion makes awareness part of the culture."],
        ["Performs all of the penetration tests", "That's a tester's role."],
        ["Writes all of the firewall rules", "That's network administration."],
        ["Approves all CVSS scores for the company", "That isn't the role."]],
      ["What is Shodan?",
        ["A search engine for internet-connected devices", "Defenders should assume attackers can find anything exposed."],
        ["A well-known IoT malware family", "Shodan is a search engine."],
        ["A NIST standard for device security", "It isn't a standard."],
        ["A password manager for teams", "It isn't a password manager."]],
      ["Which ATT&CK technique describes an attacker leaving a malicious script on a web server to maintain access?",
        ["T1505.003, Web Shell", "Web shells are a persistence foothold that must be removed during eradication."],
        ["T1552.001, Credentials In Files", "That's finding secrets in files."],
        ["T1021, Remote Services", "That's using services like SSH or RDP to move."],
        ["T1595.001, Active Scanning", "That's reconnaissance."]]
    ],

    "Incident response & remediation": [
      ["Put these actions in order: patch Apache; apply a default-deny host firewall; verify the exploit now fails; delete the backdoor account.",
        ["Firewall → delete backdoor → patch → verify", "Containment limits damage first, then remove footholds, then fix and harden, then prove it."],
        ["Patch → firewall → delete backdoor → verify", "Patching first leaves the attacker active, and patching doesn't remove backdoors."],
        ["Verify → patch → firewall → delete backdoor", "Verification comes last."],
        ["Delete backdoor → verify → firewall → patch", "Containment should come first."]],
      ["What is the goal of containment?",
        ["Limit damage while preserving evidence", "Cut the attacker's paths while keeping the host available for investigation."],
        ["Wipe and rebuild the server immediately", "That destroys evidence and skips eradication planning."],
        ["Publicly announce the breach first", "Communication matters, but containment is technical damage limitation."],
        ["Delete all logs to reduce exposure", "That destroys evidence."]],
      ["A team patches the exploited Apache server and declares the incident closed. What did they likely miss?",
        ["Eradication: backdoors, web shells, exposed creds", "The attacker may still have access through what they left behind."],
        ["Nothing; patching removes all attacker access", "It closes the original door only."],
        ["Updating the vulnerability's CVSS score", "Scores don't remove access."],
        ["Changing the compromised server's hostname", "That's obscurity."]],
      ["What is remediation verification, and why is it important?",
        ["Re-running the exploit to prove the fix works", "It's the difference between believing something is fixed and demonstrating it."],
        ["Asking the admin if they applied the patch", "That's belief, not demonstration."],
        ["Checking that the server reboots cleanly", "A reboot proves nothing about the vulnerability."],
        ["Reading the vendor's patch release notes", "Notes don't prove your system is fixed."]],
      ["After a breach, a web app's MySQL account is being reconfigured during recovery. Which change reflects least privilege?",
        ["Only the statements it needs, with a vaulted passphrase", "This limits what a stolen credential can do and keeps the secret out of code."],
        ["DBA rights, so the application never fails", "That maximizes blast radius."],
        ["No password at all, to avoid storing one", "That's insecure."],
        ["Its password stored back in config.php", "That repeats the original failure."]],
      ["How does secure configuration (hardening) act as a control?",
        ["A minimal, least-privilege baseline limits the blast radius", "Configuration determines how far a code flaw can reach."],
        ["It only matters for network devices like routers", "It applies to servers, apps, and databases too."],
        ["It replaces the need to patch software", "Both are needed."],
        ["It means enabling every feature for flexibility", "That expands the attack surface."]],
      ["In the ShopQuest case, which recovery step addresses CVE-2021-41773 directly?",
        ["Upgrade Apache off 2.4.49", "This removes the vulnerable version and reduces attack surface."],
        ["Apply a default-deny host firewall", "That's containment. It doesn't fix the flaw."],
        ["Delete the backdoor account", "That's eradication of the attacker's foothold."],
        ["Rotate the exposed API keys", "That's credential hygiene, not the CVE fix."]],
      ["Which ATT&CK technique describes an attacker using SSH or RDP to move between systems?",
        ["T1021, Remote Services", "Remote Services covers moving laterally with legitimate remote access protocols."],
        ["T1190, Exploit Public-Facing Application", "That's initial access."],
        ["T1505.003, Web Shell", "That's a persistence script on a web server."],
        ["T1552.001, Credentials In Files", "That's harvesting secrets from files."]],
      ["Which ATT&CK technique describes logging in with a device's unchanged factory account?",
        ["T1078.001, Valid Accounts: Default Accounts", "Default credentials are easily looked up and need no skill to use."],
        ["T1110, Brute Force", "No guessing is needed when the password is published."],
        ["T1059, Command and Scripting Interpreter", "That's execution after access."],
        ["T1040, Network Sniffing", "That's capturing traffic."]]
    ]
  }
});
