// Chapter 8 — Principles of Security Models, Design & Systems
// Built from the Chapter 8 notes plus the dated notes on physical security,
// travel, cloud deployment models, RAID and power.
addChapter({
  id: "ch8",
  number: "8",
  title: "Security Models, Design & Systems",
  topics: {
    "Subjects, objects & trust": [
      ["A user opens a payroll file. In access control terms, which is the subject and which is the object?",
        ["The user is the subject; the file is the object", "Subjects are active entities requesting access, and objects are the resources being accessed."],
        ["The file is the subject; the user is the object", "This reverses the roles."],
        ["Both the user and the file are objects", "The requester is a subject."],
        ["Both the user and the file are subjects", "The resource is an object."]],
      ["A process reads data from a database, then writes results to a log file. What is the process in each interaction?",
        ["A subject in both interactions", "The database and log file are the objects. An entity's role depends on whether it's requesting or being accessed."],
        ["An object in both interactions", "The process is actively requesting access."],
        ["An object when reading, a subject when writing", "It's the requester in both cases."],
        ["Neither, since processes aren't part of access control", "Processes are common subjects."]],
      ["System A trusts System B, and System B trusts System C, so System A ends up trusting System C without ever evaluating it. What is this concept?",
        ["Transitive trust", "If A trusts B and B trusts C, then A trusts C. It's convenient, but it extends trust to parties never directly vetted."],
        ["Zero trust", "Zero trust explicitly refuses implicit trust."],
        ["Defense in depth", "That's layering controls."],
        ["Separation of duties", "That's splitting critical tasks among people."]],
      ["Why is transitive trust a security risk?",
        ["One compromised party exposes everyone who trusts it", "Attackers pivot along trust chains. A weak link anywhere becomes everyone's problem."],
        ["It encrypts traffic between systems too heavily", "It isn't about encryption."],
        ["It prevents any sharing between systems", "It enables more sharing, which is the risk."],
        ["It requires MFA for every single request", "That would be closer to zero trust."]],
      ["How does the PKI certificate chain relate to transitive trust?",
        ["Root → intermediate → site: trust flows down the chain", "A compromised intermediate CA would extend fraudulent trust to every site it signs."],
        ["It's unrelated, since PKI doesn't involve trust", "PKI is built on chains of trust."],
        ["PKI avoids transitive trust by using TOFU instead", "TOFU is SSH's model."],
        ["Each site is trusted only after direct evaluation", "Browsers rely on the chain, not direct evaluation."]],
      ["A partner company's network has a trust relationship with yours. Attackers breach the partner and then reach your systems. Which design flaw was exploited?",
        ["Transitive trust with no independent verification", "Trust extended to the partner flowed on to whoever compromised it. Zero trust would verify each request."],
        ["Fail-safe design of the partner's office doors", "That's physical security."],
        ["RAID 0 striping on the partner's file servers", "That's storage."],
        ["Privacy by design in the partner's applications", "That's a privacy principle, not the flaw here."]]
    ],

    "Open vs. closed systems": [
      ["Which describes a closed system?",
        ["Proprietary, narrowly interoperable, and hard to integrate", "An example is apps built only for Apple's ecosystem. Closed systems can be harder to attack but are harder to integrate."],
        ["Built on published standards and integrates widely", "That's an open system."],
        ["Its source code is published for anyone to review", "That's open source."],
        ["A system with no network connections at all", "That's an air-gapped system."]],
      ["An organization needs systems from many vendors to interoperate easily. Which is the better fit?",
        ["Open systems", "Open systems are designed to work with others."],
        ["Closed proprietary systems", "Closed systems have narrow interoperability."],
        ["Air-gapped systems", "Isolation prevents interoperability."],
        ["Systems with secret protocols", "Secret protocols hurt interoperability."]],
      ["Which is a typical trade-off of an open system compared to a closed one?",
        ["Easier integration, but a more visible attack surface", "Openness makes integration easy and invites scrutiny, which helps defenders and attackers alike."],
        ["Open systems can't communicate with other vendors", "That describes closed systems."],
        ["Open systems never need any security controls", "They need controls like anything else."],
        ["Closed systems always integrate better than open ones", "Closed systems integrate poorly."]],
      ["What is the difference between open source and closed source?",
        ["Open source publishes its code; closed source hides it", "Open source tends to have larger developer communities."],
        ["Open source has no license; closed source does", "Open source software is licensed too."],
        ["Closed source software is always more secure", "Hiding code isn't proof of security."],
        ["Open source can't be used for commercial work", "Much open source is used commercially."]],
      ["A vendor claims its closed-source product is secure \"because no one can see the code.\" Which principle does this contradict?",
        ["Kerckhoff's principle (no security by obscurity)", "Security should hold even if the design is known. Hidden code may conceal weaknesses rather than remove them."],
        ["Defense in depth", "Layering isn't the issue."],
        ["Least privilege", "That's about access rights."],
        ["Transitive trust", "That's about trust chains."]],
      ["Closed systems are described as \"possibly more secure.\" What is the reasonable interpretation?",
        ["Fewer interfaces can help, but secrecy alone isn't security", "Less exposure can help. Relying on hidden design is obscurity."],
        ["They are always immune to vulnerabilities", "Closed systems have vulnerabilities too."],
        ["Hidden code can never be reverse-engineered", "It can be reverse-engineered."],
        ["They don't ever need patching", "They need patching too."]]
    ],

    "APIs & API keys": [
      ["What is an API?",
        ["A defined interface that lets software exchange data", "APIs connect back-end services, apps, and devices."],
        ["A type of network firewall appliance", "It isn't a firewall."],
        ["A hardware chip that encrypts data", "That's a TPM or HSM."],
        ["A family of self-spreading malware", "It isn't malware."]],
      ["What does an API key primarily do?",
        ["Identify the calling project or app", "API keys handle project identification and authorization to call an API, but they aren't strong user authentication."],
        ["Encrypt all data the API returns", "TLS encrypts transit. The key identifies the caller."],
        ["Prove the identity of the human user", "API keys identify projects or apps, not users."],
        ["Replace the need for TLS", "Keys sent without TLS can be stolen."]],
      ["Why are API keys considered less secure than auth tokens?",
        ["Static secrets tied to a project, not a verified user", "Tokens (e.g., OAuth) are usually short-lived, scoped, and tied to an authenticated identity."],
        ["API keys are always shorter than 8 characters", "Length isn't the issue."],
        ["Auth tokens are never transmitted over a network", "Tokens are transmitted."],
        ["API keys are encrypted with the weak MD5 algorithm", "That isn't what makes them weaker."]],
      ["What is the difference between project identification and project authorization for an API?",
        ["Who is calling vs. whether they're allowed", "Knowing who's calling is different from allowing what they're calling."],
        ["They are the same check", "They're distinct steps."],
        ["Identification encrypts; authorization hashes", "Neither involves encryption or hashing."],
        ["Authorization happens before identification", "You identify before you authorize."]],
      ["A valid API key is used to request /records/88, which belongs to a different customer. What must the API still check?",
        ["Whether this caller is authorized for that specific record", "A valid key identifies the project. It doesn't mean every object belongs to the caller (the same lesson as IDOR)."],
        ["Nothing; a valid key grants access to everything", "That's broken access control."],
        ["Only that the key is longer than 32 characters", "Key length doesn't authorize objects."],
        ["Whether the request arrived on port 80", "The port is unrelated to authorization."]],
      ["A developer commits an API key to a public GitHub repository. What should happen?",
        ["Revoke and rotate it, then use a secrets manager", "Once exposed, a key must be treated as compromised. Deleting the commit isn't enough."],
        ["Delete the commit; that fully fixes the problem", "Copies and scrapers may already have it."],
        ["Make the key longer so it's harder to guess", "The exposed key remains valid until revoked."],
        ["Nothing, since API keys are public by design", "API keys are secrets."]],
      ["A mobile app sends its API key in the URL query string over plain HTTP. What's the main risk?",
        ["Anyone on the path or reading URL logs can reuse it", "Keys must travel over TLS, preferably in headers rather than URLs, which end up in logs and history."],
        ["The key will expire sooner than normal", "Exposure doesn't change expiry."],
        ["The API will reject HTTP requests automatically", "Many APIs accept HTTP, which is why this matters."],
        ["There's no risk because the key is long", "Length doesn't help once the key is captured."]]
    ],

    "Physical security": [
      ["During a fire, an exit door must unlock so people can escape. What is this door design called?",
        ["Fail-safe", "Fail-safe defaults to protecting people: on power loss or failure, it unlocks."],
        ["Fail-secure", "Fail-secure stays locked on failure to protect assets."],
        ["Fail-open firewall", "That's a network device concept."],
        ["Duress lock", "Duress relates to coercion codes."]],
      ["A server room door must stay locked even if power fails. Which design applies?",
        ["Fail-secure", "Fail-secure protects assets by remaining locked when power or the system fails."],
        ["Fail-safe", "Fail-safe unlocks on failure, which suits life safety, not asset rooms."],
        ["Fail-soft", "Fail-soft means degraded operation, not a lock state."],
        ["Mantrap bypass", "That isn't a door failure mode."]],
      ["When fail-safe life safety and fail-secure asset protection conflict, which takes priority?",
        ["Human life safety", "People come first. Security designs must never trap people in an emergency."],
        ["Asset protection", "Assets never outrank lives."],
        ["Whichever is cheaper", "Cost doesn't override life safety."],
        ["Whichever the IT department chooses", "Life safety codes take precedence."]],
      ["An employee forced at gunpoint to open a secure door enters a special code that opens the door but silently triggers an alarm. What is this?",
        ["A duress code", "Duress codes appear to comply while alerting security."],
        ["A fail-safe override", "That's a door failure mode."],
        ["A logic bomb", "That's malware."],
        ["Two-person integrity", "That's requiring two people."]],
      ["Why does a duress code open the door rather than refusing access?",
        ["To protect the coerced person while summoning help", "Refusing could endanger the employee."],
        ["Because duress codes are just backup passwords", "They specifically signal coercion."],
        ["To routinely test the building's alarm system", "It's for real emergencies."],
        ["Because the door is designed to be fail-safe", "Door failure modes are separate."]],
      ["How might a code phrase be used in a duress system?",
        ["A pre-agreed phrase that signals coercion", "It lets someone ask for help without alerting the attacker."],
        ["A password for the guest Wi-Fi network", "That isn't duress."],
        ["A passphrase used to encrypt files", "That's a passphrase."],
        ["A phrase that disables all alarms", "Duress signals raise alarms."]],
      ["What does a UPS provide?",
        ["Short-term battery power during outages", "An uninterruptible power supply bridges brief outages and protects against data loss."],
        ["Permanent power for days at a time", "UPS batteries are short-term. Generators handle longer outages."],
        ["Encryption of the data stored on servers", "That's FDE."],
        ["Backup copies of important files", "That's backups."]],
      ["An electronic lock on a data center's main exit must let staff out during a power failure but keep outsiders from entering. What design satisfies both?",
        ["Fail-safe exit with fail-secure entry", "Doors can be designed so the inside always opens for life safety while the outside stays locked."],
        ["Fail-secure in both directions", "That could trap people inside."],
        ["Fail-safe in both directions", "That leaves the room open to anyone during an outage."],
        ["No lock at all, with a guard posted", "That's an unnecessary trade-off."]]
    ],

    "Travel security": [
      ["An executive travels abroad with a laptop full of sensitive data. Which practice best limits exposure?",
        ["Carry only needed data and encrypt the device", "Less data means less to lose, and encryption protects what remains if the device is seized or stolen."],
        ["Bring a full backup of the company file server", "That maximizes exposure."],
        ["Disable the device password for convenience", "That removes protection."],
        ["Use hotel Wi-Fi directly, without a VPN", "That exposes traffic."]],
      ["Why might a traveler bring a \"burner\" device instead of their normal laptop?",
        ["To limit what malware or monitoring can reach", "A clean, minimal device limits what can be compromised or implanted."],
        ["Burner devices are faster than laptops", "Speed isn't the reason."],
        ["Burners have stronger encryption by default", "The point is minimal exposure, not stronger crypto."],
        ["To avoid paying international roaming fees", "That isn't the security rationale."]],
      ["A traveler must work from hotel networks. What does the chapter recommend?",
        ["Work only through a VPN or the cloud", "A VPN protects traffic on untrusted networks, and cloud work limits data stored locally."],
        ["Connect directly to any open Wi-Fi", "That exposes traffic to interception."],
        ["Copy all files locally first", "That increases exposure on the device."],
        ["Disable encryption to speed up connections", "That removes protection."]],
      ["A laptop was left alone in a hotel room and may have had hardware or software implanted. What is the safest assumption on return?",
        ["Assume compromise; inspect or reimage it first", "Malware and monitoring devices are real travel risks."],
        ["It's fine because it was password-protected", "A password doesn't stop physical tampering."],
        ["It's fine if the screen looked normal on return", "Implants are designed to be invisible."],
        ["Only check it if it starts running slowly", "Compromise often has no visible symptoms."]],
      ["A border agent demands an employee unlock a laptop. Which pre-trip decision most reduces the impact?",
        ["Traveling with only the minimum data needed", "You can't be compelled to expose data that isn't on the device."],
        ["Storing all files in a hidden folder", "Hidden folders are obscurity and easily found."],
        ["Renaming the sensitive files beforehand", "Renaming doesn't protect content."],
        ["Disabling the screen lock to save time", "That makes things worse."]],
      ["A traveler is offered a free USB charging cable and drive at a conference booth. What is the safest action?",
        ["Decline it; untrusted devices can carry malware", "Removable media is a named malware distribution channel."],
        ["Plug it in to check what's on it", "That's exactly how infections happen."],
        ["Use it only for charging, since cables can't carry malware", "Malicious cables and drives can deliver payloads."],
        ["Plug it into a work laptop, because it has antivirus", "Signature AV can miss novel or polymorphic malware."]]
    ],

    "Cloud deployment models": [
      ["Which cloud deployment model uses infrastructure shared by many unrelated customers and operated by a provider?",
        ["Public cloud", "Public cloud is multi-tenant infrastructure offered to anyone, like AWS, Azure, or GCP."],
        ["Private cloud", "Private cloud is dedicated to a single organization."],
        ["Community cloud", "Community cloud is shared by organizations with common concerns."],
        ["Hybrid cloud", "Hybrid combines models."]],
      ["Several state agencies with shared compliance requirements jointly use one cloud environment. Which model is this?",
        ["Community cloud", "A community cloud serves a specific group with shared concerns such as mission, security, or compliance."],
        ["Public cloud", "Public cloud is open to anyone."],
        ["Private cloud", "Private cloud serves a single organization."],
        ["Hybrid cloud", "Hybrid mixes deployment models."]],
      ["A company keeps sensitive workloads in its own data center but bursts to a public provider during peak demand. Which model is this?",
        ["Hybrid cloud", "Hybrid combines private (or on-prem) and public resources."],
        ["Community cloud", "Community cloud is shared by a group of organizations."],
        ["Public cloud only", "Part of the workload stays private."],
        ["Private cloud only", "It also uses a public provider."]],
      ["A bank runs cloud infrastructure dedicated solely to itself for maximum control. Which model is this?",
        ["Private cloud", "Private clouds serve one organization, whether hosted on-prem or by a provider."],
        ["Public cloud", "Public cloud is multi-tenant."],
        ["Community cloud", "That's shared among a group."],
        ["Hybrid cloud", "Hybrid mixes models."]],
      ["In any cloud model, who is responsible for securing the customer's data, identities, and configurations?",
        ["The customer (shared responsibility)", "Providers secure the underlying infrastructure. Customers secure what they put in and configure."],
        ["The provider, entirely", "Customers keep significant responsibility."],
        ["No one; the cloud is secure by default", "Misconfigurations are a leading cause of cloud breaches."],
        ["The customer's ISP", "ISPs carry traffic and aren't responsible for cloud configs."]],
      ["A multi-tenant public cloud adds which specific risk mentioned in Chapter 1?",
        ["A malicious co-tenant in an upstream position", "Shared infrastructure means other tenants are potential adversaries."],
        ["No risk, since tenants are fully invisible", "Isolation can fail, as with VM escape."],
        ["Tenants share passwords automatically", "That isn't how cloud works."],
        ["Data is never encrypted in public clouds", "Encryption is widely available."]],
      ["A startup wants the lowest upfront cost and fastest scaling, with no hardware to manage. Which deployment model fits best?",
        ["Public cloud", "Public cloud offers pay-as-you-go capacity with the provider operating the infrastructure."],
        ["Private cloud", "Private cloud requires dedicated resources and more upfront investment."],
        ["Community cloud", "Community cloud requires a group of organizations with shared needs."],
        ["On-premises data center", "That means buying and managing hardware."]]
    ],

    "RAID & availability": [
      ["Which RAID level stripes data across drives for performance but provides no redundancy?",
        ["RAID 0", "Striping splits data across drives so reads and writes happen in parallel. If any drive fails, all data is lost."],
        ["RAID 1", "RAID 1 mirrors for redundancy."],
        ["RAID 5", "RAID 5 adds distributed parity."],
        ["RAID 6", "RAID 6 adds double parity."]],
      ["Which RAID level duplicates data across drives so an identical copy survives a drive failure?",
        ["RAID 1", "Mirroring keeps a full copy on each drive."],
        ["RAID 0", "Striping has no redundancy."],
        ["RAID 5", "RAID 5 uses parity, not full mirrors."],
        ["JBOD", "Just a Bunch Of Disks has no redundancy."]],
      ["Which RAID level stripes data with distributed parity and survives the loss of one drive?",
        ["RAID 5", "Parity lets the array rebuild a failed drive's data from the remaining drives."],
        ["RAID 6", "RAID 6 uses double parity and survives two drive failures."],
        ["RAID 0", "RAID 0 has no parity."],
        ["RAID 1", "RAID 1 mirrors rather than using parity."]],
      ["An array must survive two simultaneous drive failures using parity. Which level fits?",
        ["RAID 6 (double parity)", "Two parity blocks allow reconstruction after two failures."],
        ["RAID 5", "RAID 5 tolerates only one failure."],
        ["RAID 0", "RAID 0 tolerates none."],
        ["RAID 1 with two drives", "A two-drive mirror tolerates one failure."]],
      ["Which RAID level combines mirroring and striping for both performance and redundancy?",
        ["RAID 10 (1+0)", "It stripes across mirrored pairs, giving speed and fault tolerance at the cost of capacity."],
        ["RAID 0", "RAID 0 stripes with no mirroring."],
        ["RAID 5", "RAID 5 uses parity."],
        ["RAID 1 only", "RAID 1 mirrors with no striping."]],
      ["How does parity allow data recovery in RAID?",
        ["Missing data is recomputed from the others plus parity", "If one drive fails, its contents are recomputed from the others plus parity."],
        ["It keeps a full mirror copy of each drive", "That's mirroring."],
        ["It encrypts the data spread across the drives", "Parity isn't encryption."],
        ["It compresses the data to save disk space", "Parity adds data. It doesn't compress."]],
      ["A company uses RAID 1 and claims it no longer needs backups. What is wrong with this?",
        ["RAID mirrors deletions and ransomware too", "RAID provides availability, and backups provide recovery. You need both."],
        ["Nothing; RAID 1 fully replaces backups", "Mirrors copy mistakes and malware too."],
        ["RAID 1 doesn't provide any redundancy", "It does provide drive-level redundancy."],
        ["RAID 1 encrypts data so it can't be restored", "RAID 1 doesn't encrypt."]],
      ["Which CIA property do RAID and a UPS primarily support?",
        ["Availability", "Both keep systems running through drive failures and power outages."],
        ["Confidentiality", "Neither hides data."],
        ["Integrity", "They don't verify data correctness."],
        ["Nonrepudiation", "That's a signature property."]]
    ],

    "Secure design principles": [
      ["What does \"privacy by design\" mean?",
        ["Building privacy in from the start", "Privacy is a default design requirement throughout the lifecycle."],
        ["Adding a privacy policy page after launch", "That's after the fact."],
        ["Encrypting data only once a breach occurs", "That's reactive."],
        ["Collecting as much data as possible for analytics", "That contradicts data minimization."]],
      ["A new app collects only the data needed for its function and sets the strictest privacy options by default. Which principle is this?",
        ["Privacy by design", "Users shouldn't have to take action to be protected."],
        ["Security by obscurity", "That's about hiding design."],
        ["Transitive trust", "That's about trust chains."],
        ["Fail-safe design", "That's a failure mode."]],
      ["Each account, process, and service gets only the access needed to do its job. What principle is this?",
        ["Least privilege", "It limits damage if any one account is compromised."],
        ["Defense in depth", "That's layering controls."],
        ["Open design", "That's about publishing designs."],
        ["Transitive trust", "That's about trust chains."]],
      ["No single employee can both create a vendor and approve payments to it. What principle is this?",
        ["Separation of duties", "Splitting critical tasks prevents one person from committing fraud alone."],
        ["Least privilege", "Least privilege limits rights, but splitting a process between people is separation of duties."],
        ["Fail-secure", "That's a failure mode."],
        ["Privacy by design", "That's about privacy defaults."]],
      ["A system ships with all unnecessary services disabled and the strongest settings enabled out of the box. What principle is this?",
        ["Secure defaults", "Systems should be secure without the user having to harden them."],
        ["Fail-open", "That's the opposite of secure behavior."],
        ["Security by obscurity", "That's hiding design."],
        ["Transitive trust", "That's trust chains."]],
      ["When an authentication service crashes, the application denies all logins instead of letting everyone in. Which principle is this?",
        ["Fail secure (fail closed)", "On failure the system defaults to denying access rather than granting it."],
        ["Fail open", "Fail open would let everyone in."],
        ["Fail-safe door design", "For doors, fail-safe means unlocking for life safety, which is a different context."],
        ["Separation of duties", "That's splitting tasks."]],
      ["Why is \"keep it simple\" (economy of mechanism) a security principle?",
        ["Fewer parts mean fewer places for flaws to hide", "Complexity is the enemy of security."],
        ["Simple systems never need any patching", "They still need patching."],
        ["Simple systems are always cheaper to run", "Cost isn't the security rationale."],
        ["Complex systems are always more secure", "Complexity usually increases risk."]],
      ["What is the principle of open design?",
        ["Security shouldn't depend on a secret design", "This is the general form of Kerckhoff's principle. Strength comes from keys and controls, not hidden mechanisms."],
        ["All systems must be released as open source", "It doesn't require open source."],
        ["Anyone may access any data in the system", "That's not access control."],
        ["Firewalls should allow all traffic by default", "That's not a design principle."]],
      ["Which design approach eliminates implicit trust based on network location?",
        ["Zero trust", "Every request is authenticated and authorized regardless of where it originates."],
        ["Perimeter-only security", "Perimeter models trust everything inside."],
        ["Transitive trust", "That expands implicit trust."],
        ["A flat network", "Flat networks maximize implicit trust."]],
      ["What principle requires complete mediation?",
        ["Check authorization on every access, not just the first", "Cached or skipped checks let revoked or unauthorized access slip through."],
        ["Check access only once, at login time", "That skips later checks."],
        ["Check access once per day for each user", "Checks must happen on every access."],
        ["Let administrators bypass the checks", "That violates complete mediation."]],
      ["A company protects its database with a firewall, network segmentation, host hardening, encryption, and monitoring. Which principle does this illustrate?",
        ["Defense in depth", "Independent layers mean no single failure exposes the asset."],
        ["Security by obscurity", "None of these relies on hiding the design."],
        ["Transitive trust", "That's about trust chains."],
        ["Fail-open design", "That's about failure behavior."]],
      ["A system lets a user do exactly what they need, but the code it runs can only perform a narrow set of operations. Which pair of principles is at work?",
        ["Least privilege and the rule of least power", "Limit both what an account may do and what your constructs are capable of doing."],
        ["Transitive trust and open design", "Neither describes limiting capability."],
        ["Fail-safe and fail-secure design", "Those are failure modes."],
        ["Privacy by design and RAID", "These are unrelated."]]
    ],

    "Security models": [
      ["Which security model enforces confidentiality with the rules \"no read up\" and \"no write down\"?",
        ["Bell-LaPadula", "Bell-LaPadula protects confidentiality: subjects can't read higher-classified data or leak data to lower levels."],
        ["Biba", "Biba protects integrity (no read down, no write up)."],
        ["Clark-Wilson", "Clark-Wilson enforces integrity through well-formed transactions."],
        ["Brewer-Nash", "Brewer-Nash prevents conflicts of interest."]],
      ["Which model protects integrity with \"no read down\" and \"no write up\"?",
        ["Biba", "Biba prevents low-integrity data from contaminating higher-integrity data."],
        ["Bell-LaPadula", "Bell-LaPadula is the confidentiality model."],
        ["Brewer-Nash", "That's the Chinese Wall conflict-of-interest model."],
        ["Take-Grant", "Take-Grant models rights transfer."]],
      ["Under Bell-LaPadula, a Secret-cleared user tries to write a report into an Unclassified folder. Why is it blocked?",
        ["The *-property (no write down)", "Writing down could disclose classified data to less-cleared users."],
        ["The simple security property (no read down)", "The simple property blocks reading up, not down."],
        ["Biba's rule against writing up", "This scenario is about Bell-LaPadula, and it's a write down."],
        ["Unclassified folders are read-only for everyone", "The rule is about classification flow."]],
      ["Which model enforces integrity using well-formed transactions, constrained data items, and separation of duties, and is common in commercial systems?",
        ["Clark-Wilson", "Users manipulate data only through certified programs (transformation procedures), never directly."],
        ["Bell-LaPadula", "That's military-style confidentiality."],
        ["Biba", "Biba uses integrity levels, not transactions."],
        ["State machine model", "That's a general model of secure states."]],
      ["A consultant who accessed Bank A's confidential data is automatically blocked from Bank B's data, a direct competitor. Which model is this?",
        ["Brewer-Nash", "Access changes dynamically based on prior access to prevent conflicts of interest."],
        ["Bell-LaPadula", "That's based on static classification levels."],
        ["Biba", "Biba is about integrity levels."],
        ["Clark-Wilson", "Clark-Wilson is about transactions."]],
      ["What does a state machine model require?",
        ["Every state and transition must be secure", "If every state is secure, the system stays secure regardless of its inputs."],
        ["The system must have exactly two states", "There's no fixed number."],
        ["Each state must be encrypted at rest", "States aren't about encryption."],
        ["Users choose which state the system is in", "Transitions must be controlled."]],
      ["The Bell-LaPadula simple security property states what?",
        ["No read up", "This prevents subjects from viewing data above their clearance."],
        ["No write down", "That's the *-property."],
        ["No read down", "That's Biba's simple integrity property."],
        ["No write up", "That's Biba's *-integrity property."]],
      ["An organization's main concern is preventing unauthorized modification of financial records, not secrecy. Which model family fits best?",
        ["Integrity models like Biba or Clark-Wilson", "These focus on preventing improper modification."],
        ["Bell-LaPadula, the confidentiality model", "Bell-LaPadula focuses on confidentiality."],
        ["Brewer-Nash on its own", "Brewer-Nash addresses conflicts of interest."],
        ["No model; encryption alone is enough", "Encryption alone doesn't enforce authorized modification."]]
    ],

    "Trusted computing concepts": [
      ["What is the trusted computing base (TCB)?",
        ["The components that enforce the security policy", "If anything in the TCB fails, security can't be guaranteed, so it should be as small and verifiable as possible."],
        ["Every application installed on the system", "Only the security-enforcing components count."],
        ["The user password database on the system", "That's one asset, not the TCB."],
        ["The cloud provider's physical data center", "That isn't the definition."]],
      ["What is a reference monitor?",
        ["The concept that mediates every access to every object", "It must be always invoked, tamperproof, and small enough to verify."],
        ["A tool for viewing security logs", "That's a tool, not a reference monitor."],
        ["A passive network tap on a link", "That's capture hardware."],
        ["A single rule in a firewall", "Rules are policy. The reference monitor is the enforcing concept."]],
      ["What is the security kernel?",
        ["The TCB parts that implement the reference monitor", "The kernel is the concrete implementation that mediates all access."],
        ["The kernel's graphics and display drivers", "That isn't the security kernel."],
        ["A kernel-level rootkit hiding in memory", "Rootkits subvert kernels."],
        ["The CPU's on-chip cache memory", "That's hardware, not the concept."]],
      ["What is a security perimeter in the context of the TCB?",
        ["The boundary between the TCB and the rest of the system", "Communication across it must go through secure, controlled interfaces."],
        ["The fence around the building's grounds", "That's a physical perimeter, not the TCB concept."],
        ["The organization's edge firewall", "That's a network perimeter."],
        ["The organization's DMZ subnet", "That's network segmentation."]],
      ["Why does process isolation matter for system security?",
        ["One process can't read or corrupt another's memory", "Isolation contains faults and malicious code."],
        ["It makes the CPU run noticeably faster", "It's about separation, not speed."],
        ["It encrypts all of the network traffic", "That's TLS."],
        ["It removes the need for authentication", "It doesn't."]],
      ["A TPM seals a disk key to the verified boot state. Which security capability of systems does this illustrate?",
        ["Trusted hardware providing a root of trust", "Hardware-based keys and measured boot give a foundation software alone can't."],
        ["Security by obscurity in hardware", "The TPM uses real cryptography."],
        ["Transitive trust between devices", "That's trust chains between parties."],
        ["Fail-open design of the boot process", "That's the opposite."]]
    ]
  }
});
